### ISSUE TITLE
「新型コロナウイルス感染症が心配なときに」の印刷ページのＱＲコードが東京のＵＲＬ

### ISSUE THREAD

**Issue by YasushiIS** [code4nara/covid19#102]
## 起こっている問題 / The Problem
- 「新型コロナウイルス感染症が心配なときに」の印刷ページのＱＲコードが東京のＵＲＬ

## スクリーンショット / Screenshot

問題のＱＲコード　https://upbeat-volhard-740574.netlify.com/site-qr.svg

## 期待する見せ方・挙動 / Expected Behavior
- 奈良版まとめサイト（ https://stopcovid19.code4nara.org/ ）のＱＲコードに差し替える

## 起こっている問題の再現手段 / Steps to Reproduce
開発ページで以下の操作を行う
1. 新型コロナウイルス感染症が心配なときに」を表示
2. 右上の「印刷する」をクリックすると右上にＱＲコードが表示される。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kwaka1208** [comment]
作れます。今夜にでもPR送ります。担当assignしてください。

**Comment by YasushiIS** [comment]
aska さんに作ってもらったＱＲコード画像をマージします。

**Comment by YasushiIS** [comment]
#104 の修正と合わせて milton さんにお任せします。
