### ISSUE TITLE
色の修正

### ISSUE THREAD

**Issue by y-chan** [code4nara/covid19#111]
## 起こっている問題 / The Problem
- 色が奈良県版に合っていないグラフ/図がある

## 期待する見せ方・挙動 / Expected Behavior
- 奈良県版の色に合わせる

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by miiton** [comment]
👇参考です

- 奈良県章規定: `#581D28`
- 奈良県の公式ページの県章の色: `#7B3652`
- 現在サイトで使っている色: `#85005D`

![flow-print sketch 2020-04-10 10-40-16](https://user-images.githubusercontent.com/468745/78954633-b1763600-7b17-11ea-9850-af663573ef2f.png)

**Comment by miiton** [comment]
👆補足です

- コントラスト比はいずれもAAAでした（W3CのWebアクセシビリティ基準）
- 個人的には規定の色はベースカラーと区別がつきにくいのかな？

👇Colorblind Simulationの結果も貼ります（全種網羅しているわけではないです）

![Stark 2020-04-10 10-47-46](https://user-images.githubusercontent.com/468745/78954984-ca331b80-7b18-11ea-82d6-8bb37aba559d.png)

![Stark 2020-04-10 10-48-30](https://user-images.githubusercontent.com/468745/78954997-d5864700-7b18-11ea-8b57-ce8e0406d48a.png)

![Stark 2020-04-10 10-49-04](https://user-images.githubusercontent.com/468745/78955026-e9ca4400-7b18-11ea-9900-6f16b86b64a0.png)

**Comment by miiton** [comment]
画像だけ貼って意見を述べていませんでした。

👆の画像を貼った経緯が、Slackで県章の規定を参考に出していただいた事から、一度再考を促すという意図で貼りました。
私の意見としてはWebアクセシビリティの観点を優先するべきだと思うので、現状の `#85005D` で統一するのが良いと思っています。
