### ISSUE TITLE
奈良県内の動向の「入院患者の状況」表を見やすく修正する

### ISSUE THREAD

**Issue by YasushiIS** [code4nara/covid19#116]
## 改善詳細 / Details of Improvement
- 奈良県内の動向の「入院患者の状況」表を見やすく修正する

## スクリーンショット / Screenshot

![入院患者数の状況(案)](https://user-images.githubusercontent.com/6837346/78977237-c6bc8600-7b52-11ea-8f2f-a7a6fc35ca85.png)

## 期待する見せ方・挙動 / Expected behavior
- スクリーンショットように面積で全体割合が把握しやすい表が表示される。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by YasushiIS** [comment]
slackで相談中。改善案がきまればそのデザインに修正する。

**Comment by YasushiIS** [comment]
今日（4/27|）の報道発表のPDFでは、感染者数の状況表の「症状のない方」が無くなり、重症、宿泊療養、自宅療養が増えてます。このため、暫定として、どんな状況表にするか、ソースをPDFベースにするか、オープンデータベースにするか、を早く決めたいです。
個人的には、図の形状にはこだわりなく、オープンデータベースが自動更新に移行できるので良いのではと考えてます。

**Comment by heimax222** [comment]
オープンデータの元データが報道発表という構図になってまして、オープンデータの項目を今後どうするか早速相談が来ています。ですので、状況表については報道発表ベースで進める形でお願いします。

**Comment by heimax222** [comment]
おそらく、オープンデータの項目は報道発表から消えたものについては今後は空白で、増えたものにについては項目が追加される形で進むと思います。

**Comment by YasushiIS** [comment]
取り急ぎdeta.jsonは触らず表示文言のみ方法発表ＰＤＦに合わせて添付図のように修正します。最終形をどうするかは議論・取りまとめください。
オープンデータの項目が変更された場合は、エクセルjson変換スクリプトも修正が必要ですが、本票の改善案か決まってから修正する手順で考えてます。
![クリップボード一時ファイル02](https://user-images.githubusercontent.com/6837346/80378745-12ec2200-88d8-11ea-9ab6-dc1cc8f6d2e5.png)

**Comment by heimax222** [comment]
報道発表の方も、レイアウトを真似てきましたね。この形になるように追従してみます？
![image](https://user-images.githubusercontent.com/35659901/80423717-6fbcfc00-891b-11ea-80e1-0c482c2f258f.png)

**Comment by YasushiIS** [comment]
報道発表のデータ項目が、オープンデータのエクセルに含まれるようになるなら賛成です。

**Comment by YasushiIS** [comment]
報道発表のデータをスプレッドシートに入力し、そこから json を作るようにしてみました。
作ったJSONを添付します。
[data.json.txt](https://github.com/code4nara/covid19/files/4578538/data.json.txt)

**Comment by heimax222** [comment]
奈良県版と奈良市版で状況表を共有している件については、どういう方向で進めましょう？その方向性が決まれば、いただいたjsonを参照するように現在提案中の状況表で進めてみましょうか？
![image](https://user-images.githubusercontent.com/35659901/81031818-8d183a00-8ec8-11ea-9ad8-d8b80b94885a.png)

**Comment by YasushiIS** [comment]
添付された表を表示する場合は、奈良市の奈良県の状況表は別デザインにせざるを得ないでしょう。
県と市のデータの項目が異なるので、別の方が見やすくできるでしょう。

**Comment by YasushiIS** [comment]
奈良県の状況表の改善案を含む更新案です。

![クリップ奈良県](https://user-images.githubusercontent.com/6837346/81182261-84b72080-8fe8-11ea-851c-6c5c55b8c41e.png)

**Comment by YasushiIS** [comment]
現状、対応している人がいないのと、２か月以上進展がないので、一旦クローズにします。
再検討する場合は、reopen か再起票ください。
