### ISSUE TITLE
サイドバーの順序の変更と整理

### ISSUE THREAD

**Issue by YasushiIS** [code4nara/covid19#118]
## 改善詳細 / Details of Improvement
- サイドバーの順序を使いやすいように変更する

## スクリーンショット / Screenshot

![Clipboard01](https://user-images.githubusercontent.com/6837346/78980767-8b718580-7b59-11ea-9bdf-dc469ead074a.jpg)

## 期待する見せ方・挙動 / Expected behavior
変更案
- 「奈良県総務部知事公室防災統括室」を削除（特に情報が集まっているページでないため）
- 「企業の皆様・はたらく皆様へ」を「中小企業・小規模事業者の皆さまへ」に変えて
http://www.pref.nara.jp/#007　へのリンクに変更（メンテナンスされていないため）
- 「お子様をお持ちの皆様へ」を削除（内容と一致していないため）
- 「他自治体の対策サイト」は #38 で協議中のものをこちらにマージ
案１）表記を「他地域の対策サイト一覧」に修正し、 リンク先を一覧表になっている
https://github.com/tokyo-metropolitan-gov/covid19/blob/development/FORKED_SITES.md
にする。（北海道版、愛知県版など）
案２）リンク自体を削除する（大阪府版、兵庫県版など）

- 順序の入れ替え（案）
------------------------------
奈良県内の最新感染動向
奈良市内の最新感染動向
（セパレータ）
新型コロナウイルス感染症が心配なときに
（セパレータ）
奈良県公式ホームページ（県へのリンク）
奈良県内各市町村の関連ページ
（セパレータ）
県民の皆様へ（県へのリンク）
中小企業・小規模事業者の皆さまへ（県へのリンク）
（セパレータ）
一般電話窓口（県へのリンク）
帰国者・接触者相談センター（県へのリンク）
教育委員会の発表（県へのリンク）
労働関係の電話相談（県へのリンク）
（セパレータ）
当サイトについて
他地域の対策サイト一覧
------------------------------

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by heimax222** [comment]
・「奈良県公式ホームページ」と「県民の皆様へ」はリンク先が同じため、「県民の皆様へ」を削除
・「奈良県公式ホームページ」と「奈良県内各市町村の関連ページ」の間に、「知事記者会見（令和2年4月9日）」を追加し、 http://www.pref.nara.jp/module/105696.htm へのリンクとする。
・以降、知事のコロナに関する会見がある度に、リンク先と日付を変更。
・「帰国者・接触者相談センター」「一般電話窓口」「労働関係の電話相談」の位置を移動
・「学校の休校情報」の追加
・他地域の対策サイト一覧の下に、大阪府、京都府、三重県、和歌山県の隣接府県を別だし

以上です。上記改定案後の姿を以下に示します。
***
<h2>
 奈良県内の最新感染動向<br>
 奈良市内の最新感染動向<br>
（セパレータ）<br>
新型コロナウイルス感染症が心配なときに<br>
　帰国者・接触者相談センター（県へのリンク）<br>
　一般電話窓口（県へのリンク）<br>
（セパレータ）<br>
奈良県公式ホームページ（県へのリンク）<br>
　知事記者会見（令和2年4月9日）（県へのリンク）<br>
奈良県内各市町村の関連ページ<br>
（セパレータ）<br>
中小企業・小規模事業者の皆さまへ（県へのリンク）<br>
労働関係の電話相談（県へのリンク）<br>
（セパレータ）<br>
教育委員会の発表（県へのリンク）<br>
学校の休校情報<br>
（セパレータ）<br>
当サイトについて<br>
他地域の対策サイト一覧<br>
　大阪府<br>
　京都府<br>
　和歌山県<br>
　三重県<br>
</h2>

**Comment by YasushiIS** [comment]
@heimax222 さんの案から近県を抜いた状態でいったんサードバーメニューを整理し、やはり必要となったら追記しましょう。

近府県４県を抜く理由は
・他の自治体リンクからたどることができる
・和歌山は更新が止まっているように見える
・大阪、京都（二つとも）には他自治体サイトのリンクがない

纏めると
・「県民の皆様へ」を削除
・「知事記者会見（令和2年4月9日）」を追加　 http://www.pref.nara.jp/module/105696.htm
・「帰国者・接触者相談センター」「一般電話窓口」「労働関係の電話相談」の位置を移動
・「学校の休校情報」は #158 で追加
・「他地域の対策サイト一覧」を以下に変更
https://github.com/tokyo-metropolitan-gov/covid19/blob/development/FORKED_SITES.md

--------
奈良県内の最新感染動向
奈良市内の最新感染動向
（セパレータ）
新型コロナウイルス感染症が心配なときに
　帰国者・接触者相談センター（県へのリンク）
　一般電話窓口（県へのリンク）
（セパレータ）
奈良県公式ホームページ（県へのリンク）
　知事記者会見（令和2年4月9日）（県へのリンク）
奈良県内各市町村の関連ページ
（セパレータ）
中小企業・小規模事業者の皆さまへ（県へのリンク）
労働関係の電話相談（県へのリンク）
（セパレータ）
教育委員会の発表（県へのリンク）
学校の休校情報　                      ---(コメント：追加予定位置）
（セパレータ）
当サイトについて
他地域の対策サイト一覧
--------

**Comment by heimax222** [comment]
知事会見の内容を最新のもの(4/16)版に差し替えようと思います。

**Comment by heimax222** [comment]
知事会見の内容を最新のもの(4/28)版に差し替えようと思います。

**Comment by YasushiIS** [comment]
特に改善提案もなさそうなので、Issueはクローズします。
サイドバー項目の追加変更があれば改めて起票ください。
