### ISSUE TITLE
「新型コロナウィルス感染症が心配なときに」印刷ページの連絡先が前バージョンと重なってしまっている

### ISSUE THREAD

**Issue by miiton** [code4nara/covid19#122]
## 起こっている問題 / The Problem
- 「新型コロナウィルス感染症が心配なときに」印刷ページの連絡先が前バージョンと重なってしまっている
## スクリーンショット / Screenshot

![新型コロナウイルス感染症にかかる相談窓口について | 奈良県 新型コロナウイルス感染症対策サイト（非公式） 2020-04-10 22-26-32](https://user-images.githubusercontent.com/468745/78994277-9a1c6480-7b7a-11ea-88a2-6eb9b3d96fc5.png)

## 期待する見せ方・挙動 / Expected Behavior
- きれいに表示

## 起こっている問題の再現手段 / Steps to Reproduce
1. https://stopcovid19.code4nara.org/print/flow/ にアクセス

## 動作環境・ブラウザ / Environment
- macOS
- Chrome

**Comment by miiton** [comment]
おそらくGitHubがマージの際にsvgのコードを置き換えではなく、うまいこと（？）新旧両方残してしまったのかなと

**Comment by YasushiIS** [comment]
開発ページのフローが表示出来なくなっているのは別問題でしょうか？
https://upbeat-volhard-740574.netlify.com/naracity

**Comment by miiton** [comment]
https://upbeat-volhard-740574.netlify.com/flow

開発ページはURLの階層がおかしいみたいですね。別問題ですね。

**Comment by YasushiIS** [comment]
単に回線が遅かっただけみたいです。
開発ページでも同様になっているので、おそらくこれを修正で解消出来るでしょう。

**Comment by YasushiIS** [comment]
該当部分のコードが削除されるように見えたのですが、開発用ページでは変化ないようです。明日でも詳しく見てみます

**Comment by miiton** [comment]
最新の `development` ブランチで、`yarn dev` したものと `yarn run generate:deploy --fail-on-page-error` したものを見てみましたが反映されているようでした。netlifyのキャッシュか何かかな...？

参考: [netlifyのキャッシュ削除方法 \- Qiita](https://qiita.com/taichi0514/items/76800bc801c7759c74bc)

**Comment by YasushiIS** [comment]
参考ページの手順で３度ほどnetlifyのキャッシュクリアをしても変化がみられなかったが、データ更新のマージをすると正しく表示されるようになりました。
どこかのキャッシュの影響かもしれませんが、詳細不明。

次のリリースで本番も更新します。
