### ISSUE TITLE
入院患者数と残り病床数の円グラフ表示における総病床数が、入院患者数と残り病床数の足し算のため実際より多く示される。

### ISSUE THREAD

**Issue by heimax222** [code4nara/covid19#126]
## 起こっている問題 / The Problem
- 入院患者数と残り病床数の円グラフ表示における総病床数(右上隅)が、入院患者数と残り病床数の足し算でしめされているため、入院患者が多くなると実際の病床数より多く表示される。

## スクリーンショット / Screenshot

病床数は24床であるが、入院者数が27名になったため、総病床数が27床と示されている。
![image](https://user-images.githubusercontent.com/35659901/79000400-81ff1200-7b87-11ea-94ca-6b7cb8783f11.png)

## 期待する見せ方・挙動 / Expected Behavior
- 病床数をjsonデータに加え、入院患者数を引いて、残り病床数を求めるように処理を変更。
- 入院患者数が病床数をうわまった際(オーバーフロー時)の表示も検討しておいた方が良さそう。

**Comment by YasushiIS** [comment]
病床数以上の入院は出来ないので、優先度は低くて良いと思います。

**Comment by YasushiIS** [comment]
奈良県のオープンデータに病床数が含まれているので、この件は未対応で良いと思います。
