### ISSUE TITLE
病床数の円グラフ表示の注釈文の変更

### ISSUE THREAD

**Issue by YasushiIS** [code4nara/covid19#127]
## 改善詳細 / Details of Improvement
- 注釈の変更
変更前：（注）病床数は 感染症指定医療機関 の第一・二種感染症病床の合計

## スクリーンショット / Screenshot

![Clipboard01](https://user-images.githubusercontent.com/6837346/79031817-a6d1a480-7bdc-11ea-9362-241fa930da96.jpg)

## 期待する見せ方・挙動 / Expected behavior
- 注釈の変更
変更後：（注）病床数は 新型コロナウイルス感染症への県の対応について の入院可能病床数
「新型コロナウイルス感染症への県の対応について」リンク先はhttp://www.pref.nara.jp/secure/224794/64_4.pdf

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by YasushiIS** [comment]
リンク先の資料ですがもう少し良いのを見つけました。中川さんが公開していた議事資料のベースとなったとみられる、県が公表している最新資料です。
http://www.pref.nara.jp/secure/226463/20200409tijiteirei.pdf

**Comment by moonlight-aska** [comment]
http://www.pref.nara.jp/secure/226463/20200409tijiteirei.pdf
これには入院可能病床数のってないように思いますが, これにリンクはりますか?

**Comment by YasushiIS** [comment]
11ページくらいのグラフに確保病床数が入ってます。
もともとのＰＤＦがよいか、スライドのＰＤＦが良いか、どちらにしましょう？

**Comment by moonlight-aska** [comment]
元の資料の方がまとまっていい感じはしますが...

**Comment by YasushiIS** [comment]
では元の資料 http://www.pref.nara.jp/secure/224794/64_4.pdf で行きましょう

**Comment by moonlight-aska** [comment]
ちょっと参戦します.

変更後の注釈、資料名が２度出てきて少し長いので, こんな感じではどう?
![sample01](https://user-images.githubusercontent.com/3615686/79042200-8e8b7500-7c30-11ea-9f88-eb1afd2f5e26.png)

**Comment by YasushiIS** [comment]
@moonlight-aska の画像のように修正してもらいたいという意図でした。
紛らわしい表現すいません。

**Comment by YasushiIS** [comment]
本番公開済みなのでクローズします。
