### ISSUE TITLE
OGPの差し替え

### ISSUE THREAD

**Issue by heimax222** [code4nara/covid19#13]
## 起こっている問題 / The Problem
- OGP画像データの差し替え(一旦差し替えたがnot foundになった)
- 最初に差し替えたものと、画像サイズを合わせてみてうまくいかなければ、背景色の透明が悪さしているかも。下記の期待する見せ方に貼った際も黒背景になってしまったため、白背景に直して貼りなおしました。

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/35659901/76702256-d4c1e700-670b-11ea-8909-5d91c622006a.png)

## 期待する見せ方・挙動 / Expected Behavior
![image](https://user-images.githubusercontent.com/35659901/76702329-4ac64e00-670c-11ea-935c-31ab70e216ec.png)

**Comment by YasushiIS** [comment]
https://stopcovid19.code4nara.org/ogp.png
の差し替えは完了、反映済み

**Comment by YasushiIS** [comment]
loading（初期表示時）の画像も ogp.png に変更します。
