### ISSUE TITLE
入院患者数と残り病床数の円グラフの色変更

### ISSUE THREAD

**Issue by moonlight-aska** [code4nara/covid19#135]
## 改善詳細 / Details of Improvement
- 入院患者数と残り病床数の色を奈良色「#85005D」に変更

## スクリーンショット / Screenshot
![sample02-0](https://user-images.githubusercontent.com/3615686/79043295-415fd100-7c39-11ea-84a2-f97ae0362e4e.png)

## 期待する見せ方・挙動 / Expected behavior
![sample02-1](https://user-images.githubusercontent.com/3615686/79043306-4886df00-7c39-11ea-9fa3-db185be7d511.png)

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by moonlight-aska** [comment]
別ブランチきってなかったので, Issue #127の修正がmergeされた際に, こちらの修正も取り込まれたようですね.

**Comment by YasushiIS** [comment]
本番反映されているのでクローズします。
