### ISSUE TITLE
グラフの初期表示を「日別」ではなく「累計」にしてみては

### ISSUE THREAD

**Issue by heimax222** [code4nara/covid19#14]
## 改善詳細 / Details of Improvement
- ページを開いた際に「日別」だと0件になることが多く、「累計」の方が実際の感覚に近い数値なため、「累計」で表示されるようにしてみてはどうか。

**Comment by YasushiIS** [comment]
現状は検知件数が少ないので累計にしても良いと思います。しかし、将来的に件数が多くなれば、より重要なのは累計ではなくその変化なので、状況がどう変わっているわかりやすい「日別」に戻す方向で進めましょう。

**Comment by YasushiIS** [comment]
奈良県でも連日陽性者が報道されいる状態で、「日別」に戻しています。
当面この状態ですすめるおし、issueはクローズします。
