### ISSUE TITLE
各カードの更新時間がデータ更新時間ではなく、システム更新時間になっている。

### ISSUE THREAD

**Issue by heimax222** [code4nara/covid19#151]
## 改善詳細 / Details of Improvement
- 各カードの更新時間がデータの更新時間ではなく、システムビルド時のシステム時間となっている。

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/35659901/79128672-e831a200-7dde-11ea-824f-232c01f7f1af.png)

## 期待する見せ方・挙動 / Expected behavior
- 各カードの更新時間はデータを更新した時間である方が望ましい。

**Comment by YasushiIS** [comment]
データの「更新」時刻は
１）元データを作成した時刻
２）スプレッドシートに反映した時刻
３）システムに反映した時刻
と考えられ、現状は３のデータ変換した時刻です。これを１）の元データを作成した時刻を表示するなら、その情報の入力するフィールドが必要です。

個人的にはシステムへのデータを反映は、その時点でシステム側で知っている最新データが反映されているので、あえて変えなくても良いと考えます。

**Comment by heimax222** [comment]
私の意図しているデータの更新時間は現状だと２）が一番近いです。県が公表した時間に近いものが良いかなと考えました。現状はデータ更新に関係なくシステム側の修正でビルドすると更新時間が進むように見えたのですが違いますか？

**Comment by heimax222** [comment]
今後、県や市の固定URLを定期実行で参照しに行くのであれば、そこで更新が確認できたタイミングが適当かと思います。ファイル内に書かれた手入力の更新時間より、確実かなと思ったり。

**Comment by miiton** [comment]
報道資料(PDF)の作成日時・更新日時を取るという手も（画像はpdfcpuコマンド）

![~ 2020-04-15 21-31-28](https://user-images.githubusercontent.com/468745/79337466-86994100-7f60-11ea-86eb-3bc6be29211a.png)

**Comment by heimax222** [comment]
更新日時もありですね。ちょっとリアリティがありすぎて、提供した方が引くかも^^;;
定期更新時の時間だといい感じの時間(公表から10分以内ぐらいでキリの良い数字)にまるめられるかなとも思ったりです。

**Comment by YasushiIS** [comment]
現状の自動更新の構成案では、特定ＵＲＬのデータ公開後の取得、サイト更新まで１０～２５分程度かかる想定です。
データ公開自体が１日１回なので、更新時刻を丸めて表示するなら時間単位で十分ではないでしょうか？　個人的には日単位でも十分と思っています。

**Comment by miiton** [comment]
http://www.pref.nara.jp/55168.htm

xlsxになったことで、👆のPDFにある日付はとれなくなりましたし、表中の👇の部分も `=NOW()` が仕込まれているので使えないですね

![奈良県_01新型コロナウイルス感染者_患者リスト (1) numbers 2020-04-25 08-49-20](https://user-images.githubusercontent.com/468745/80265298-13b36700-86d2-11ea-88f4-a0b212076ae3.png)

> 個人的には日単位でも十分と思っています。

私も元データ自体が日足なので時間は不要かなと思いました。

**Comment by YasushiIS** [comment]
公開されたエクセルをダウンロードしてきて、そここあら読み込んだ「最終更新_年月日時間」を使う場合でも now() は問題になるでしょうか？　編集・保存しないと値は変わらないので大丈夫と思っていました。、

**Comment by heimax222** [comment]
>データ公開自体が１日１回なので、更新時刻を丸めて表示するなら時間単位で十分ではないでしょうか？　個人的には日単位でも十分と思っています。

日時ぐらいでどうでしょうか。データ取り込みを行った時間が例えば17時15分であれば、17時にするか18時にするかといったところはどうでしょう？私は切り上げで、18時で良いと思います。

**Comment by YasushiIS** [comment]
調査したところ、前回のコメントとはことなり、やはり now() が問題でした。いまのオープンデータのエクセルだと、データを更新した時刻ではなくアクセスした現在の時刻が入ります。ここを修正しない実際の更新時刻が取れないので、日付ならともかく時間表示は意味をなさないと思います。
また、現時点（4/25 18:50）の公開データは昨日4/24のデータが含まれてないようで、現在の手作業しているサイト情報より古くなります。このあたりどう運用するか検討すべきかもしれません。

**Comment by heimax222** [comment]
更新時間はデータを公式から引っ張ってきた時間(概ね公表された時間)で良いと思うのですが、作成した時間へこだわる必要ありますか？

>また、現時点（4/25 18:50）の公開データは昨日4/24のデータが含まれてないようで、現在の手作業しているサイト情報より古くなります。このあたりどう運用するか検討すべきかもしれません。

はい。自動で取り込むのは少し様子をみた方が良いと思います。オープンデータで公開されることにはなりましたが、どうやって更新していくかは(更新マニュアルをつくって数人で体制をつくる)これからなのではと思います。

**Comment by YasushiIS** [comment]
取り込み方法次第で「公式から引っ張ってきた時間」が「(概ね公表された時間)」にならないので、クリアにすべきと思ってます。
GitHub action 実行時にダウンロード＆変換すると、引っ張ってくる時間＝デプロイした時間なので、公表時間と関係なくなります。

**Comment by heimax222** [comment]
>更新時間はデータを公式から引っ張ってきた時間(概ね公表された時間)

cronの定期実行でファイルの更新を監視し、更新されていればdata.jsonを更新することを想定していて、この時にdata.jsonの中の更新時間をその時のシステム時間に更新するのは難しいのかな？？そもそもデータの更新時間が、デプロイした時間になることの方が不思議な感じです。

**Comment by YasushiIS** [comment]
前提が齟齬ってるようです。jsonの更新は、cron定期実行をかんがえてますが、 cronを使わずgithub actionでの実行でjson変換も可能です。（現在のスプレッドシートからの変換がactionでの実行）
もしGitHub  actionでjson 変換する場合、その実行時にデータを取得し変換するので、取得時間＝action実行時間＝デプロイ時間であり、これ以外の更新時間は（現状では）わかりません。
一方、cron実行前提で、実行時に更新チェックし、更新検知した時刻をjson内に記録する処理を入れて運用する手順であれば問題ありません。

**Comment by heimax222** [comment]
データの更新タイミングとシステムの更新タイミングが違うため、データの更新とシステムの更新を分けた方が良いと思うのですが。GitHub actionsのみで、それができるのであればcronを使わなくても良いと思います。現状だと、データは更新されてないのに、システムの修正などの更新を行うと、データ更新時間が進んでませんか？GitHub actionsにも時間による定期実行もあるようなので、ここでデータの更新を確認する処理を走らせて、システムの更新と分けられればそれで良いと思うのですが難しいのかな？

**Comment by YasushiIS** [comment]
データの更新とシステムの更新を分けた方が良いと思う
ここは賛成だがactionではこうp

**Comment by YasushiIS** [comment]
データ更新とシステム更新のタイミングの話と、データ更新ーデプロイ時間の話は独立です。データ更新とシステム更新を分けるだけでは、データ更新時刻がデプロイ時刻になる場合がある、という問題は解決しません。（現状ですね）
分けた方が良いというのは賛成です。念のため

**Comment by heimax222** [comment]
>データ更新時刻がデプロイ時刻になる場合がある
>データの更新とシステムの更新を分けた方が良い

というのが皆さんの共通認識になったのであれば、後の技術的な話はシステムの更新フローの整理と一緒に考えた方が良いのかも。issueの#176かslackの#covid19nara-devで議論していた更新フローをどうするかの新たなissueを立てて、このissueは閉じても良さそうですね。

**Comment by YasushiIS** [comment]
#207 の本番リリースでカードごとの最終更新日を「日」単位で表示に変更。現状、カード単位のデータ更新時刻時刻は入手不可なのでデータが存在する最終日単位での表示にします。

一方で、ページ上部の最終更新の日時は、data.jsonを作成した日時にとし、新たなデータが追加／変更されるまで json を更新しない運用にします。
なお「最新のお知らせ」の更新では、最終更新日時は更新されません。
