### ISSUE TITLE
デプロイを手動実行出来るようにする

### ISSUE THREAD

**Issue by miiton** [code4nara/covid19#153]
## 改善詳細 / Details of Improvement
- 現状データを差し替えたいだけの時にも何かしらコードに変更を加えて `development`、 `master` にマージしないとデプロイが出来ないので、任意のタイミングでデプロイを実行できるようにする

## 期待する見せ方・挙動 / Expected behavior
- 案です
    - 「データ更新」のようなタイトルのIssueの起票やクローズなどをトリガーとして実行する（GitHubだけで完結できる）
    - Slack上でスラッシュコマンドやBotに対するメンションをトリガーとして実行する（Botを動かすサーバーが必要）
    - curlコマンドなどで無理やりrepository_dispatchイベントを発火させてそれをトリガーとして実行する（コマンドをどこで実行する？）
    - Releaseの作成をトリガーとして実行する（GitHubだけで完結できる）

経験上SlackのBotを使うパターンが一番お手軽です。IssueやReleaseだとデータのちょっとした文言修正でもいちいちGitHubの操作が必要になる＆無駄なログが残ってしまうので

トリガーにできるGitHubのeventは以下にまとまっています
https://help.github.com/ja/actions/reference/events-that-trigger-workflows

## 動作環境・ブラウザ / Environment
- GitHub Actions

**Comment by YasushiIS** [comment]
（追記）**データ更新に関わるデプロイ**に関して

＞curlなどで無理やりrepository_dispatchイベントを発火させてそれをトリガーとして実行

公開に使っているサーバでデータ変換の一連の処理で、curl でトリガーを引く方法が、簡単にデータ更新を自動化できると思います。具体的には以下のような処理。

1.  所定ＵＲＬからデータファイルをダウンロード（curl）
2. データ更新の有無を確認
3. 更新があればjson生成
4. repository_dispatchイベントを発生（curl）

**Comment by miiton** [comment]
あああ、 `repository_dispatch` だめですね...

[Events that trigger workflows \- GitHub Help](https://help.github.com/en/actions/reference/events-that-trigger-workflows#external-events-repository_dispatch)

> Note: This event will only trigger a workflow run if the workflow file is on the master or default branch.

ブランチの指定ができないみたいです

**Comment by miiton** [comment]
でも `deployment` もcurlで叩けるのでそっちの方向で用意しますね

**Comment by miiton** [comment]
↓やり方です

あらかじめ [Personal Access Tokens](https://github.com/settings/tokens) を作成してください。

# 開発にデプロイするcurl

```
curl -X POST -H "Authorization: token ${GITHUB_TOKEN} " \
             -H "Content-Type: application/json" \
             https://api.github.com/repos/code4nara/covid19/deployments \
             --data '{"ref": "development", "environment": "development"}'
```

# 本番にデプロイするcurl

```
curl -X POST -H "Authorization: token ${GITHUB_TOKEN} " \
             -H "Content-Type: application/json" \
             https://api.github.com/repos/code4nara/covid19/deployments \
             --data '{"ref": "master", "environment": "production"}'
```


deploymentステータスを更新するという処理を忘れていましたので修正します
