### ISSUE TITLE
リンクページを新たに作成する

### ISSUE THREAD

**Issue by kwaka1208** [code4nara/covid19#155]
## 改善詳細 / Details of Improvement
- 奈良県にも新型コロナウイルス関連の情報提供サイトが増えてきたので、それらの情報を集約するページを作成する。

## 期待する見せ方・挙動 / Expected behavior
- 以下のページに記載のリンク先を分類し、探しやすいように配置する。  
http://naramaga.in/node/523
- 上記ページ以外にも有用なサイトが有れば適宜リンクを追加
- リンク先は別タブ・別ウインドウで表示する。
- 情報提供先も掲載する（Googleフォームを別途作ろうかなと）

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by YasushiIS** [comment]
この件、一旦、kwaka1208 にアサインしますね。

**Comment by shige2313** [comment]
「奈良持ち帰りごはん」アプリ(Webサイト？)がリリースされました
https://nara-mochikaeri.glideapp.io/
店舗からの申し込みによる情報掲載ではなく、facebookグループでテイクアウト利用者がアップロードした情報による情報掲載となっています。
近鉄奈良・JR奈良駅近辺が対象ですが、アプリ自体は複製できる・データベースはgoogleスプレッドシートなので他地域でも流用可能です(他府県でも同じアプリで展開しているところもあります)。

**Comment by YasushiIS** [comment]
現状、対応できる人がいないのと２か月以上進展がないので一旦クローズにします。
必要がある場合などは reopen して下さい。
