### ISSUE TITLE
トップページの最終更新の時刻が表示されていない

### ISSUE THREAD

**Issue by YasushiIS** [code4nara/covid19#160]
## 起こっている問題 / The Problem
- トップページの最終更新の時刻が表示されていない

## スクリーンショット / Screenshot

![Clipboard01](https://user-images.githubusercontent.com/6837346/79441123-cec46c00-8011-11ea-96aa-99da46698bc8.jpg)

## 期待する見せ方・挙動 / Expected Behavior
- トップページの最終更新の時刻を表示する
この時刻は、「デプロイ時刻」もしくは「データの最終更新時刻」がよさそうに思います。

## 起こっている問題の再現手段 / Steps to Reproduce
1.トップページの表示

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by miiton** [comment]
ここはデプロイ時刻でいいですよね？

**Comment by miiton** [comment]
> この時刻は、「デプロイ時刻」もしくは「データの最終更新時刻」がよさそうに思います。

すいません、これを読み飛ばしていました...

**Comment by miiton** [comment]
sheet2jsonの出力時にlastUpdateが空になっているのが原因でした。
修正しましたので次のデプロイで直ったのを確認、もしくは公式xlsxからの自動取得時に反映できていれば本件クローズできると思います

**Comment by YasushiIS** [comment]
調査ありがとうございます。
対応は、news.json と同じく、公開サーバでデータの更新を判定し、更新されていればjsonに自動変換後、curlでgithub Actionを起動し生成されたjsonを取り組む、という流れで進めていきたいと思います。

**Comment by YasushiIS** [comment]
#207 による data.json の差し替えで反映できるように更新できたのでクローズします。
