### ISSUE TITLE
奈良県又は奈良市向けの共通データフォーマットの検討

### ISSUE THREAD

**Issue by heimax222** [code4nara/covid19#163]
## 改善詳細 / Details of Improvement
奈良県と奈良市から公開されているデータを整理して、将来的な自動化に向けた共通のデータフォーマットを検討する。

検討用のたたき台
https://drive.google.com/open?id=1ZC84JhQPARFiAKOX41AQTp9pb41QEQIa

シートは陽性者を確認したタイミングで更新する「陽性者リスト」と、日々の集計結果をまとめる「コロナ検査情報」の2枚を用意。議論しやすいように、それぞれの項目の意図で色分けした議論用のシートも用意しています。前半のシートはCodeforJapanの下山さんの方で用意いただいた、項目定義の定義仕様書で、それらを参考に後半の入力用シートを作成しています。自治体職員でも入力しやすいようにexcelにしており、外部公開時にcsvも必要かの議論もお願いします。

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/35659901/79453855-39cb6e00-8025-11ea-9c19-649a80570006.png)
![image](https://user-images.githubusercontent.com/35659901/79454036-857e1780-8025-11ea-9cd6-5e819d45a037.png)

## 期待する見せ方・挙動 / Expected behavior
こういう項目があればや、これだとシステムに取り込みにくいなど、意見がありましたらよろしくお願いします。県や市からの問い合わせが来てますので、こういったシートをベースにした意見交換を近々行う予定です。

**Comment by YasushiIS** [comment]
現在、奈良市さんからもらっているデータシートは、GitHub のsampleに置いているものです。
このエクセルからの変換ツールは既に作っていて、covid19-Nara-tools リポジトリに登録しています。
項目はほぼ同じなので、改造で済むと考えてます。

https://github.com/code4nara/covid19-nara-tools/blob/develop/sample/opendata_covid19_NaraCity.xlsx

**Comment by heimax222** [comment]
一つ気になっているのは、ファイル内に最終更新日時があった方が良いかなということで、セルの左上にエクセルのnow()関数で、自動更新の日時を入れています。ファイル自体は書き込み用パスワードを設定した状態のエクセルで公開するか、それぞれutf8のカンマ区切りでCSV化して出すかですが、CSV化した場合は1行目が 最終更新日時,2020-04-06,,,,,,,,,,,のまま出すか、CSVの方は最終更新日時の行を無くしてだすかなども考えられるかと。あると邪魔という方は是非ご指摘ください。

**Comment by YasushiIS** [comment]
留意点として、公開時点で患者リストの全員の「患者_状態」項目が最新でないと、表示している「症状のある方」と「症状のない方」の集計が正しくなくなります。
（追記）
患者_退院済フラグも正しく指定されてないと、「亡くなられた方」などの集計が合わなくなります。陽性患者表は日々入力するシートの最終日を参照することで表示自体は問題なさそうです。

**Comment by heimax222** [comment]
「患者_状態」及び「患者_症状」については、随時更新するとなると現状の体制では厳しいのかなと思うところと、陽性が判明した時点での症状がわかることの意味とで迷った結果、項目としては残し、陽性確認時のみとしました。また一旦、記者発表したものを変更するのも難しいと思われるため、現状の発表形式だと途中で過去の情報を変更することは難しいと思います。現状を表すパラメータとしたい場合は、退院済みフラグ同様に赤にしてフラグ化した方が良いですが、今度は判断を誰がするかでもめると思います。病床が程度に分かれて管理されるようになったら、カウントしやすくなるんですけども、その場合も個人をトレースしつづけるのは限界がありますよね。おそらく、赤に指定したものは採用されない(こちらとしても管理体制ができるまではお勧めしない)と思っています。東京とかはどうやって管理してるんだろう？？？

**Comment by YasushiIS** [comment]
「入院者数(現在)」と「入院者中の患者数」と「 入院者中の無症状病原体保有者数」の違いがどこかで定義されてます？　定義書を見る限り記述はないようでした。おそらく「入院者中の患者数」は、「症状のある方」という意味だと思いますが、あってますか？

もう一点細かな点ですが、東京案(CFJ案？)だと、カッコ（）を使わずに単語を _ でつないでいますが、この様式に合わせなかった理由はありますか？

**Comment by YasushiIS** [comment]
奈良市版の修正案をこちらに置きました。
https://drive.google.com/file/d/1xi3SKRZ-No2Ol29Ur6uoKS-sHXPP6mVU/view?usp=sharing
変換ツールの修正は、データが届いてから行います。

**Comment by heimax222** [comment]
>「入院者中の患者数」は、「症状のある方」という意味だと思いますが、あってますか？

あってます。定義側の更新ができてないので、追加しておきます。県発表の報道資料の定義に合わせた形になります。

>もう一点細かな点ですが、東京案(CFJ案？)だと、カッコ（）を使わずに単語を _ でつないでいますが、この様式に合わせなかった理由はありますか？

ありがとうございます。その辺りの意識が抜けてましたので、様式と見比べてみます。

**Comment by heimax222** [comment]
県や市がデータをオープンにしてくれた場合も、C4ANで、全ての項目を使わなければいけないということはないです。統計処理をされる方や、他の可視化表現をされる方もおられると思うので、できるだけ多様な方が使いやすいように、出せる範囲がどこかや、出す場合はどういう表現が適当かを、一緒に考えてもらえそうかなということで、少ないチャンスを活かすためにも先に考えておこうというものです。

**Comment by heimax222** [comment]
ファイルを更新しました。主な変更点は以下の通りです。
①項目のサブタイトルの表記の接続記号をアンダーバーに統一しました。
②日々更新で行うコロナ検査状況のシートに追加していた項目の定義を、06.各種集計シートに記載。このため病床数の定義が06.から07.となりました。
③サブタイトルに現在とつけていたものを削除。公表時の現在値を示すものが大半で、それ以外のものについてサブタイトルを付けるように変更。現時点で「現在値」以外は「累計」のみ。

**Comment by YasushiIS** [comment]
ＣＳＶの最終更新日に関して
RFC4180によるcsvフォーマットは、「先頭行にファイルの先頭には、オプションとして、通常行と同一の書式を持つ、ヘッダ行が存在してもよい」なので、一般的なライブラリは、先頭行を項目名として扱うように実装されています。なので、１行目に最終更新日時で２行目に項目名だと、多くの場合そのまま処理できず一手間かける必要があると思います。
参考：https://tools.ietf.org/html/rfc4180
データフォーマットという観点では、最終更新日を含めない表形式のほうが綺麗ではあります。

**Comment by heimax222** [comment]
CSVの件、アドバイスありがとうございます。CSV形式での出力の議論になった場合は、最終更新日を外す方向で進めます。

**Comment by shige2313** [comment]
奈良県がデータを公開しました
http://www.pref.nara.jp/55168.htm

**Comment by YasushiIS** [comment]
奈良県からオープンデータが公開されたデータのフォーマットはFIXされていると考えられるので Issue はクローズします。
