### ISSUE TITLE
各表・グラフにデータ提供元を表示

### ISSUE THREAD

**Issue by YasushiIS** [code4nara/covid19#168]
## 改善詳細 / Details of Improvement
- 各表・グラフにデータ提供元（奈良県／奈良市など）を表示

## スクリーンショット / Screenshot

![Clipboard01](https://user-images.githubusercontent.com/6837346/79628000-e61d6980-8177-11ea-879f-3c6236c82c8c.jpg)

## 期待する見せ方・挙動 / Expected behavior
- データ元が分かるように表示
- オープンデータのＵＲＬがあればリンクを追加
- 現在、県と市のグラフカードは共用しているので、表記内容次第で分ける必要があるかも。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by YasushiIS** [comment]
以下の方向で進めたいと思います。
・奈良県のデータと奈良市のデータが同じカードを使っているので、これをわける。
・奈良市版の各カードの「発生状況について 」に変えて「奈良市提供のデータを利用」との文言を追加
・奈良市の「陽性者の属性」に「（注）日付は発表日ベースで記載」、「陽性者数グラフ」に「（注）奈良市提供データに基づきグラフ化。発表日と異なります。」と追記
・奈良県版はデータが提供され次第、同様の文言・リンクを追加

**Comment by heimax222** [comment]
>・奈良県版はデータが提供され次第、同様の文言・リンクを追加

この出典元のリンクの追加を急いだ方が良いかも。自動化できていなくても、参照元を明示することは可能ですので。リンク先はファイルが実際に置いてあるページ( http://www.pref.nara.jp/55168.htm )でどうでしょうか？

**Comment by YasushiIS** [comment]
修正のほうこうせいとしては、コンポーネントのグラフの中で、コメント（noteの文字列を表示、無ければ表示なし）と、引用元へのリンク（新しく追加した変数sourceの文字列を表示し、リンク先は既存のurl）のようにすると、すべてのグラフで共用できると思います。

**Comment by YasushiIS** [comment]
カードの中で、グラフ下にコメント（大阪版みたいにnoteの文字列を表示、なければ表示無し）。
引用元へのリンク（新しく追加した変数source(？)の文字列を表示し、リンク先は既存のurl）のようにすると、奈良市／奈良県とも同じグラフを共用できると思います

**Comment by YasushiIS** [comment]
「報道発表の日付と一致しないデータがあります」は、奈良県ではなく奈良市の「陽性者の属性」に表示する。
