### ISSUE TITLE
入院患者数及び陽性患者数をそれぞれ入院者数と陽性者数に変更。

### ISSUE THREAD

**Issue by heimax222** [code4nara/covid19#171]
## 改善詳細 / Details of Improvement
- 「奈良県内の最新感染動向」のページで表示される各カードのタイトルを、奈良県の報道資料にも説明のある、患者と感染者の使い分けに合わせて「入院者数」と「陽性者数」に変更する。

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/35659901/79641389-36291a00-81d2-11ea-8104-36b0c340857a.png)

## 期待する見せ方・挙動 / Expected behavior
・「入院患者数」と記載の2箇所を「入院者数」に変更。
・「陽性患者数」と記載の2箇所を「陽性者数」に変更。

**Comment by heimax222** [comment]
修正しようかと思い全体を「患者」で検索をかけました。
県部分と奈良市部分の表示部、それから東京からの名残でdata.json系のファイルにも見えますね。
奈良市も患者と感染者を使い分けてますので、この機会に奈良市版と奈良県版の表現も合わせておきたいですね。data.json系のデータファイルについては自動生成ツールの方で修正すべきか、元データを参照してるのかによって、修正箇所が変わる感じでしょうか。

**Comment by YasushiIS** [comment]
現状は、data.jsonは covid19-nara-theet2jsonリポジトリを使いgoogleスプレッドシートから、GitHub action実行時に自動生成しており、開発版も公開版も同じ処理です。
一方、data_naracity.json は、covid19-Nara-tools の変換スクリプトで生成しており、action実行時に取り込んでいて、いまは本番、開発版とも同じです。（news.jsonも）
内部表現も全て修正するなら、これらも修正が必要になるので、とりあえず一番簡単な対応として表示文言のみの差し替えが良いと思います。
本格的な対応は、オープンデータとして公開されるフォーマットが決まり、jsonにどんな値を入れるか決めてからまとめて対応するのが効率的と思います。

**Comment by heimax222** [comment]
了解です。では後ほど表示文言のみ修正して送るようにします。

**Comment by YasushiIS** [comment]
表示修正は完了しまいた。
コード内の表現の修正は、該当する部分の改良が入ったときに行い、当面は現状のままで進めていきたいと思います。
これで問題なければクローズください＞@heimax222
