### ISSUE TITLE
「陽性者の属性」表に発症年月日、職業、状態、症状を追加する

### ISSUE THREAD

**Issue by YasushiIS** [code4nara/covid19#175]
## 改善詳細 / Details of Improvement
- 「陽性者の属性」表に発症年月日、職業、状態、症状を追加する

## 期待する見せ方・挙動 / Expected behavior
-「陽性者の属性」表に発症年月日、職業、状態、症状を追加
新しい報道発表の公表項目が増えているので、表に表示可能な項目を追加する。
参考：
・報道発表　http://www.pref.nara.jp/secure/227163/0421houdou.pdf
・現状スプレッドシートに入力している項目は以下の通り
No | 全国地方公共団体コード | 都道府県名 | 市区町村名 | 公表_年月日 | 発症_年月日 | 患者_居住地 | 患者_年代 | 患者_性別 | 患者_職業 | 患者_状態 | 患者_症状

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by moonlight-aska** [comment]
県のオープンデータには発症年月日はありますが, 職業, 状態, 症状はないですね.
発症年月日が必要なら変換ツールでdata.jsonに入れるようにしますが...

**Comment by YasushiIS** [comment]
データがあれば表示する／しないは、コード修正で簡単に対応できるので、公開データにある項目は全てjsonに入れておいた方が自由度が高いと思います。

**Comment by YasushiIS** [comment]
現状、対応できる人がいないのと２か月以上進展がないので一旦クローズにします。
データ項目は可能な範囲で、covid19-nara-tools の変換ツールで data.json に入れるようにして、コード修正だけで反映させる方向で進めます。
