### ISSUE TITLE
奈良県オープンデータのエクセルからjsonへの自動変換・自動デプロイ

### ISSUE THREAD

**Issue by YasushiIS** [code4nara/covid19#176]
## 改善詳細 / Details of Improvement
- 奈良県オープンデータのエクセルからjsonへの自動変換スクリプトを用意
- オープンデータの更新を検知し、json変換後、GitHub Action を実行させるスクリプトを用意
- これらのスクリプトを本番サーバで一定時間毎に cron 実行させる

## 期待する見せ方・挙動 / Expected behavior
- オープンデータの更新、お知らせの更新を検知し、自動で公開サーバに半得させる
例えば１０分おきにデータ更新を検知し、更新があるデータのjsonを更新し、curlコマンドで、GitHub Action を実行しデプロイする。

## 動作環境・ブラウザ / Environment
- CentOS7

** 補足
奈良県オープンデータのエクセルから作成するのは deta.json で、#116などの表示方法の変更があるまでは同じ内容とし、
patients（患者リスト）は、患者リストから作成、date は最終更新j時刻、dataは公開項目すべてを含める。そのほかは患者集計表から作成　patients_summary は日付と陽性確認_件数をリスト化する。
ですすめる、でいかがでしょうか。

**Comment by moonlight-aska** [comment]
県のオープンデータをdata.json, sickbeds_summary.jsonに変換するツールをcovid19-nara-toolにPRしておきました.
sickbeds_summary.jsonをdata.jsonへの統合は今回はしてません. 
sickbedsのタグ名の追加とlast_update->lastUpdateのタグ統一が必要かと.

**Comment by moonlight-aska** [comment]
sickbeds_summary.jsonのデータを以下のようにdata.jsonに統合し, sickbeds_summary.jsonを廃止したいと思いますが, 表示側の処理の変更お願いしたいです.

          {
            "attr": "退院した方",
            "value": 30
          },
          {
            "attr": "亡くなられた方",
            "value": 1
          }
        ]
      }
    ]
  },
  "sickbeds_summary":{
    "date": "2020/04/24 18:29",
    "入院患者数": 46,
    "残り病床数": 18
  },
  "lastUpdate": "2020/04/24 18:29"
}

**Comment by moonlight-aska** [comment]
現在, 入院者数(累計)の表示に, "陽性患者数"の値を使用しているようですが, この際に"入院患者数累計"に変更してはどうですか?

  "main_summary":{
    "date": "2020/04/24 18:29",
    "attr": "検査実施人数",
    "value": 0,
    "children": [
      {
        "attr": "陽性患者数",
        "value": 77,
        "children": [
          {
            "attr": "入院患者数",
            "value": 46,
            "children": [
              {

**Comment by moonlight-aska** [comment]
オープンデータの変換やってて気づいたのですが, 陽性者数パネルの日々のデータをエクセル内の最終更新日まで作成しているのだが, 陽性者が出なくなってエクセルが更新されなくなると, グラフが最終更新日までしか描画されない.
県のオープンデータは新規に陽性者が出るとか, 変化が生じないと多分更新しないですよね.
このパネルのデータに関しては, 毎日自動変換するなら, 変換する前日まで新規陽性者が0でもデータを作るようにした方がよい気がしてきました.

**Comment by YasushiIS** [comment]
sickbeds_summary.json ですが、data.json に下のような日別表記をいれて、日別変化のグラフで表示するというのはどうでしょうか？

 ```
 "sickbeds_summary": {
    "date": "2020/04/25 22:00",
    "data": [
      {
        "日付": "2020-04-01T00:00:00.000Z",
        "入院数": 0,
        "病床数": 0,
      },
　　　：
    ]
 }
```

グラフのイメージはこんな感じ。（表しているものは違いますが）

![クリップボード一時ファイル01](https://user-images.githubusercontent.com/6837346/80336423-2bd1e480-8892-11ea-8183-6038f70b6de4.png)

**Comment by YasushiIS** [comment]
"陽性患者数"⇒"入院患者数累計"の変更は賛成です。

もう一点の、変換前日までの扱いですが、

> このパネルのデータに関しては, 毎日自動変換するなら, 変換する前日まで新規陽性者が0でもデータを作るようにした方がよい気がしてきました.

「データが（まだ）ない」と「０」とは意味が異なり、後から追加される可能性もあるので難しい所です。ツールでの自動生成では公開されたデータそのままで良いように思います。
確認できた情報があれば、手動で簡単にjsonに反映させられる仕組みができればなおよいとおもます。

**Comment by moonlight-aska** [comment]
[data.zip](https://github.com/code4nara/covid19/files/4539881/data.zip)

とりあえず, 入院患者と病床数の日別変化グラフの開発用にdata.json作ってみました.
 "sickbeds_summary":{
    "date": "2020/04/24 18:29",
    "data": [
      {
        "日付": "2020-01-24T08:00:00.000Z",
        "入院者数": 0
        "病床数": 0
      },
      {
        "日付": "2020-01-25T08:00:00.000Z",
        "入院者数": 0
        "病床数": 0
      },

**Comment by YasushiIS** [comment]
奈良県のデータに関しては、現状公開されているエクセルに数字のない項目があり、今後変更される可能性があるため、当面は、現状通り、GoogleSpreadSheet から Json を作成するフローで運用します。
jsonを、Github Action で取り組むように修正したワークフローを #205 #207 で更新。いったん運用に入ることにし、Issueをクローズします。

見せ方に関しての「ベッド数の日々の状態」グラフなどは別に議論・検討しましょう。
