### ISSUE TITLE
 奈良市の感染動向の「陽性者グラフ」の日時情報が左下になっている

### ISSUE THREAD

**Issue by YasushiIS** [code4nara/covid19#189]
## 起こっている問題 / The Problem
- 奈良市の感染動向の「陽性者グラフ」の日時情報が右下でなく左下になっている。

## スクリーンショット / Screenshot

![クリップボード一時ファイル01](https://user-images.githubusercontent.com/6837346/80569808-a3d81000-8a34-11ea-9c04-23e5490046e7.png)

## 期待する見せ方・挙動 / Expected Behavior
- 奈良市の感染動向の「陽性者グラフ」の、日時情報が右下に表示される

## 起こっている問題の再現手段 / Steps to Reproduce
1. ブラウザで表示

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by heimax222** [comment]
ざっと見た感じで、note以下はフッターとして一括定義で自動レイアウトになっているため、細かな調整はできない(すると全体に影響が及んだり、レスポンシブル対応にも影響が出そう)ですので、noteの記載内容の変更を提案します。

note：陽性結果は陽性確認日で表記。
title ：陽性者数(奈良市確認分のみ)

**Comment by YasushiIS** [comment]
合計を含め、陽性者リストの数と表の数がなぜ異なるのか、この説明では分からないと思います。スタイルのためにここまで短くするよりは、現状維持の方がより正確で分かり易いと思います。

**Comment by YasushiIS** [comment]
奈良市の感染状況ページ自体が削除されているので、このIssueもクローズします。
