### ISSUE TITLE
緊急事態宣言延長(予定)に伴う学校休業情報の更新

### ISSUE THREAD

**Issue by moonlight-aska** [code4nara/covid19#194]
## 改善詳細 / Details of Improvement
5/4に予定されている緊急事態宣言延長に伴う学校休業情報の更新.
これに伴い#158はいったんCloseでよいかと..

## 期待する見せ方・挙動 / Expected behavior
5/3時点の各自治体, 私立学校等のHPからわかる範囲でスプレッドシートのデータをアップデートしたので, GitHub Pagesの一覧表を更新する.
公立学校はこちらの情報も...
https://this.kiji.is/628547578885194849?c=476913576246887521

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kwaka1208** [comment]
後ほど更新します

**Comment by kwaka1208** [comment]
更新しました。ところで、この情報って誰向けなんでしたっけ？

**Comment by YasushiIS** [comment]
この Issue はクローズしてよろしいでしょうか？

**Comment by kwaka1208** [comment]
前のIssueもそうでしたが、アップデートごとにやりとりしているので残していただけますか。

**Comment by shige2313** [comment]
更新情報が上がってました
https://this.kiji.is/631435150320239713?c=476913576246887521

**Comment by kwaka1208** [comment]
反映しました。
https://note.crssrds.jp/school_info/

**Comment by YasushiIS** [comment]
緊急事態宣言が解除されており、更新の必要はないと考えるのでクローズします。
