### ISSUE TITLE
合計病床数が異なっている。

### ISSUE THREAD

**Issue by YasushiIS** [code4nara/covid19#198]
## 起こっている問題 / The Problem
- 合計病床数が、陽性患者数プラス残り病床数て計算されていて実数よりも宿泊療養者数分多い。

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/6837346/80961654-5b5e8f00-8e46-11ea-8477-4570a3ac132a.jpeg)

## 期待する見せ方・挙動 / Expected Behavior
- 合計病床数を入院患者数プラス残り病床数とする。
- 合わせて、病床数jsonをdata.jsonに統合、陽性者表の項目も県発表の項目に合わせる。

## 起こっている問題の再現手段 / Steps to Reproduce
1. トップページの表示

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by heimax222** [comment]
注釈の表記が「奈良市オープンデータ」となってます。左下に「奈良県の公開情報を利用」のリンクがるため、注釈自体が不要かも。

**Comment by YasushiIS** [comment]
文言は削除の方向で、データは、#116 に添付した json を参照する方向で修正します。

**Comment by YasushiIS** [comment]
#116 #117 に投稿したjson形式で対応する予定です。
