### ISSUE TITLE
各市町村の対策ページ

### ISSUE THREAD

**Issue by YasushiIS** [code4nara/covid19#2]
## 改善詳細 / Details of Improvement
- 各市町村の対策ページへのリンクの追加
小中学校, 保育園等に関しては市町村管轄なので情報をたどる先として大事...

「他自治体の対策サイト」に並列して各市町村の対策ページへのリンクを集めたページを追加

既知のもの）
奈良市：https://www.city.nara.lg.jp/site/coronavirus/
生駒市：https://www.city.ikoma.lg.jp/category/20-0-0-0-0.html
天理市：個別のお知らせのみで, まとまったページなし
橿原市：あまり有益な情報ないが, 一応ここかな
　　　　https://www.city.kashihara.nara.jp/article?id=5e2f7de865909e3290f741a8
桜井市：https://www.city.sakurai.lg.jp/cyumoku/1582883925848.html
大和高田市：http://www.city.yamatotakada.nara.jp/life/kenko/coronavirus.html

**Comment by moonlight-aska** [comment]
[covid19_url_list.xlsx](https://github.com/code4nara/covid19/files/4332813/covid19_url_list.xlsx)
とりあえず, 一通りリストアップしました.
