### ISSUE TITLE
スマホ画面でのハンバーガーメニューの説明を追加する

### ISSUE THREAD

**Issue by YasushiIS** [code4nara/covid19#215]
## 改善詳細 / Details of Improvement
- お知らせの下もしくは上に、ハンバーガーメニューの説明を表示する。

## スクリーンショット / Screenshot

![クリップボード一時ファイル01](https://user-images.githubusercontent.com/6837346/81466506-359e0500-920d-11ea-8a70-af9556598b15.png)

## 期待する見せ方・挙動 / Expected behavior
- 例えば、「スマホの左上のボタンでメニューが開きます」など文言を追加
- 理想は、レスポンスシブデザインによりハンバーガーメニューになったときだけ表示

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by heimax222** [comment]
新規感染者数の急減を受けて、出口戦略の議論が高まると思われますので、ここに5月5日発表の奈良県対処方針へのリンクを張ろうと思うのですがいかがでしょう？決して警戒を緩めようという意図ではありません。
一方で、この場所にはスマホ向けにサイドバーへの案内をとの話でしたが、上の理想にもあるように「レスポンスシブデザインによりハンバーガーメニューになったときだけ表示」がすぐにできそうにないため、できる目途が立つまでの暫定処置で取り急ぎ入れられればと思います。

**Comment by YasushiIS** [comment]
メニューの案内と出口戦略の表示は、目的が全く異なるので別Issueで進めるのが妥当だと思います。

**Comment by YasushiIS** [comment]
対応できる人がいなく、２か月以上進展がないので、一旦クローズします。
