### ISSUE TITLE
陽性者グラフで 5/9 の1名分のデータが表示されれていない。

### ISSUE THREAD

**Issue by YasushiIS** [code4nara/covid19#216]
## 起こっている問題 / The Problem
- 5/9 1名のデータが表示されれていない。
感染者リストには反映されていて、読み込だサーバの data.json には、5/9のデータは「最後のデータとして」ある

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/6837346/81466932-3c7a4700-9210-11ea-92d0-1c863302dcd9.png)

## 期待する見せ方・挙動 / Expected Behavior
- 5/9 1名のデータ（最新日のデータ）が表示される。

## 起こっている問題の再現手段 / Steps to Reproduce
1. トップページの表示
https://upbeat-volhard-740574.netlify.app/

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by miiton** [comment]
https://upbeat-volhard-740574.netlify.app/

私の画面ではおかしくないように見えます

![image](https://user-images.githubusercontent.com/468745/81467948-1d32e800-9217-11ea-9058-2a120068f4a6.png)

**Comment by YasushiIS** [comment]
この Issue の現象は、ローカル環境の yarn でも再現したので起票しましたが、時間がたてば正しく表示されるようになりました。
見た限りではソースを現在時刻に依存するようなコードはなく、また今日の更新でも再現しなかったので対応なしとし、しばらく様子を見ることにします。

**Comment by YasushiIS** [comment]
5/13のデータ更新直後に再現。
もう一度デプロイすれば、修正されたのでキャッシュまわりがあやしい？

**Comment by YasushiIS** [comment]
参考：この要因だと思われます。
https://qiita.com/kazuomatz/items/9af1f2135ef70283c00f#%E8%BF%BD%E8%A8%98
