### ISSUE TITLE
「陽性者の属性」の居住地がすべて「不明」と表示されている

### ISSUE THREAD

**Issue by moonlight-aska** [code4nara/covid19#217]
## 改善詳細 / Details of Improvement
- 5/9時点で, 「陽性者の属性」の居住地が「不明」となっている.

## 期待する見せ方・挙動 / Expected behavior
- 居住地を正しく表示する.

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by heimax222** [comment]
奈良市側も不明となっているため、プログラム側の問題のようですね。
