### ISSUE TITLE
奈良市の各パネルの更新日が4月25, 26日のまま

### ISSUE THREAD

**Issue by moonlight-aska** [code4nara/covid19#224]
## 改善詳細 / Details of Improvement
[本番サーバ]
- 奈良市から新規感染者が出てないからデータが更新されないのだと思いますが, 奈良市の新規感染者を奈良県が先に発表することはこれからはないと思うので, 県が発表した日までは奈良市も0人とし, 更新日を変更した方法よいと思う.
以前, データが更新されないことと0であることは違うという意見がありましたが, 県が発表した以上, その傘下の市のデータは0と判断できるので.

## 期待する見せ方・挙動 / Expected behavior
- 県が発表した日までは奈良市も0人とし, 更新日を県の発表日に合わせる.

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by YasushiIS** [comment]
県が0と発表した当日の陽性者が、必ず0とはなりません。奈良市の陽性者数は発表ベースではなく結果が出た日ベースなので。それを考慮し当日分は空欄にする、あるいは、無視して0にするとルール決めすれば良いと思います。
奈良市のシートを更新すると10〜20分程度で開発サイトに反映される仕組みにしています。

もう一点、奈良市からのデータ以外も使ってる文言にした方が良いと思います。

**Comment by YasushiIS** [comment]
データ更新可能なのは陽性者のグラフと患者リストの二つですよね。
状況表は検査数があるので無理な気がします。

**Comment by YasushiIS** [comment]
現状は 5/10 のデータの更新されています。
http://stopcovid19.code4nara.org/naracity

**Comment by YasushiIS** [comment]
#249 と同じないようなのでこちらはクローズします。
