### ISSUE TITLE
サイドバーの知事会見(県の方針)のリンクの削除と移動

### ISSUE THREAD

**Issue by heimax222** [code4nara/covid19#226]
## 改善詳細 / Details of Improvement
- 【本番サイト】
- 自粛延長を受けて新たな対処方針が示されているため、知事会見のリンク情報が古くなったため。
- 今後の対処方針(5月5日発表が最新)、トップページの最新のお知らせ枠の下に掲載することで、議論が進む出口戦略の方向性を確認しやすくできればと思います。#215のハンバーガーメニューへの案内と掲載場所がかぶりますので、調整が必要です。

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/35659901/81695641-dc98d000-949d-11ea-8a76-70cee1d5a4e9.png)

![image](https://user-images.githubusercontent.com/35659901/81697111-c1c75b00-949f-11ea-8b05-51c72feb0b4e.png)

## 期待する見せ方・挙動 / Expected behavior
- サイドバーの知事会見へのリンク項目の削除
- 今後の対処方針をトップページの最新のお知らせ枠の下に掲載

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by YasushiIS** [comment]
情報が更新されるごとの修正は、ソースではなくjson等のデータファイルの更新で行うのが望ましいと考えます。データ更新であれば、ソースごと本番デプロイするより更新コストが少なくなることが期待できます。

**Comment by heimax222** [comment]
一番収まりが良かったのがここでしたので、ざっとソースを見たのですが、ソースコード埋め込みでしたので、メンテナンス的には向いてない場所なのかもですね。他にお勧めの場所はありますか？出口戦略は当面重要な情報になると思うので、目立つ場所に持ってきたいと思っています。ローカル環境ではスクショのように動作確認済みです。

**Comment by heimax222** [comment]
14日に政府から33都道府県に対して緊急事態宣言の解除が示される可能性があるのと、それを受けての対応が県から示される可能性もあるため、新たに対処方針が示される可能性もあります。

**Comment by heimax222** [comment]
askaさんに教えていただいた岡山版にある、お知らせの中の黄色枠も良いですね。岡山版のソースを見てみます。
![image](https://user-images.githubusercontent.com/35659901/81768170-4bfdd680-9515-11ea-90dc-b35ae66f0b8a.png)

**Comment by heimax222** [comment]
岡山県方式でも動きました。ざっと見た感じで、他の動作に影響は無さそうですが、リンクはコード内に埋め込みになってます。明日中に新たな対処方針の決定稿が示される予定のため、できれば明日中に、最新のお知らせ内の岡山方式か、最新のお知らせ下の枠に張り付けられたらと思います。ご意見ありまりましたら、お願いします。
![image](https://user-images.githubusercontent.com/35659901/81928591-74bec280-9620-11ea-89be-30397c3a1b32.png)

**Comment by YasushiIS** [comment]
data以下のjsonファイル参照にすれば、現状の奈良県の感染データと同じ流れで、スプレッドシートから反映という運用フローに乗せられると思います。

**Comment by heimax222** [comment]
@YasushiIS 
> data以下のjsonファイル参照にすれば、現状の奈良県の感染データと同じ流れで、スプレッドシートから反映という運用フローに乗せられると思います。

jsonファイルの参照への変更は、明日更新後に対応をお願いしても良いですか？

どちらに貼るかですが、個人的には、岡山のスーパー高校生藤原さんに敬意を表して、岡山方式で進められたらと思っています。
