### ISSUE TITLE
PCR検査数を日別累計で表示するグラフを追加する。

### ISSUE THREAD

**Issue by heimax222** [code4nara/covid19#235]
## 改善詳細 / Details of Improvement
- 奈良県からオープンデータとして公開されている「奈良県_02新型コロナウイルス感染者・患者集計表.xlsx」には、4月27日以降日別のPCR検査数が掲載されるようになっている。このデータを使って陽性者数と同じ、日別と累計の切り替え式の棒グラフで表示する。陽性者数の推移に加えて、十分な数のPCR検査数が出来ているかも大切な指標となるため。
http://www.pref.nara.jp/55168.htm

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/35659901/82466699-b4dbe480-9afb-11ea-9c64-6fea8727d83b.png)

## 期待する見せ方・挙動 / Expected behavior
- 現在公開されている4月27日～5月11日分のデータをつかって、手動で差し替えたdata.jsonからの表示の動作確認はできました。位置はとりあえず一番下に配置しています。表示位置や表現の仕方など、ご意見ありましたらお願いします。

**Comment by YasushiIS** [comment]
開発サイトに反映済みです。
https://upbeat-volhard-740574.netlify.app/
@heimax222  これで良ければクローズください。
