### ISSUE TITLE
[開発サーバ] 入院者数の状況の入院中の人数がおかしい

### ISSUE THREAD

**Issue by moonlight-aska** [code4nara/covid19#240]
## 起こっている問題 / The Problem
[開発サーバ] 入院者数の状況の入院中の人数が91人となっている. 

## スクリーンショット / Screenshot

![covid19_error01](https://user-images.githubusercontent.com/3615686/82724142-e37dd900-9d0e-11ea-8e69-6f44cddc5fde.png)

## 期待する見せ方・挙動 / Expected Behavior
- 入院中を6人に修正

## 起こっている問題の再現手段 / Steps to Reproduce
ここ開く
https://upbeat-volhard-740574.netlify.app/

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by YasushiIS** [comment]
.github/workflow のデプロイスクリプトを修正で対処。rsyncデプロイの確認時の、dev-pages へのデプロイ部分がコメントアウトされたまま残っていたので、これを元に戻し、デプロイを実行。

デプロイ時に読み込む deta.json は、奈良県のオープンデータのエクセルから自動生成に変更済みで、データとして正しいことを確認。

**Comment by YasushiIS** [comment]
開発サイトは修正・反映済みです。
本番リリース（masterブランチ）に関係する可能性もあるので、本番デプロイで問題なければ、クローズするようにします。

**Comment by YasushiIS** [comment]
本番サイトにも、2020/05/24 時点のデータが正しく反映冴えているので、チケットをクローズします。
