### ISSUE TITLE
[本番/開発サーバ] 県内市町村の関連ページのURL変更

### ISSUE THREAD

**Issue by moonlight-aska** [code4nara/covid19#242]
## 改善詳細 / Details of Improvement
[本番/開発サーバ]
奈良県内各市町村の関連ページの各市町村のURLが, 特別低額給付金などの関係もあり, コロナ情報がまとめられたり, トップページに情報を整理したりと, URLを変更した方がよい市町村が多く発生.
URLデータを更新したので, サーバに反映.
 
## 期待する見せ方・挙動 / Expected behavior
下記データをサーバに反映
データ : covid19nara/uploads/20200524_covid19_url_list.xlsx
(手元で修正したら, covid19naraがupload不可で, municipalities.xlsxに変更することができなかった)

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by YasushiIS** [comment]
googleドライブの運用に関して
直接まとめサイトのデータに反映することを想定している covid19naraフォルダ直下のファイルは、いたずら等防止のため特定のアカウントのみ編集可能としています。
municipalities.xlsx を編集したい方は、編集権限リクエストを出してください。
https://drive.google.com/file/d/1dQFcgpQqN8JG9V3cLotntp5wKmqaSdWA/view?usp=sharing

**Comment by YasushiIS** [comment]
次に、市町村関連ページのURLを含む municipalities-data.json の更新運用に関して
現状、municipalities-data.json は、github配下のjsonをそのまま使っています。
これを、Googleスプレッドシートに更新があれば自動更新するように変更するようにしたいと思いますがいかがでしょうか？
具体的には10分おきにダウンロードして差分を検出、差分があればjsonを更新後、Githubを起動。
GitHub Action で更新された json を読み込んでデプロイする、という流れです。
この方法のメリットは、稼働実績があり人手を介せず更新できること、デメリットは、シート編集中にデプロイされる可能性がある事（編集が終わった次の更新で直る）です。

**Comment by YasushiIS** [comment]
@moonlight-aska 
uploadにアップロードされたエクセルの、十津川村のリンク先が下北山村になっているようです。
また、uploadにあるxlsxでは市町村コードがなく、covid19-nara-tools の変換ツール convert_municipalities.py で json に変換できなかったので、covid19naraフォルダ直下の municipalities.xlsx のシートにコピーしました。
WIPの状態でPRを出します。

**Comment by YasushiIS** [comment]
・GoogleSpreadSheet  から municipalities.xlsx の十津川村のリンクを修正。該当ページが不明なのでトップページを設定。
・GoogleSpreadSheet からダウンロードしてjson出力するスクリプトを作成（ covid19-nara-tools/convert_municipalitiesV2.py ）
・十津川村のリンクを修正した json を作成、PR #243 でdevelopment ブランチにマージ。

**Comment by YasushiIS** [comment]
PR #247 で、平群町、川西町、宇陀市、桜井市、下市町、川上村のURL修正を反映させたと考えてます。

**Comment by YasushiIS** [comment]
現時点で対応は必要ないと考えてます。
一旦クローズして、必要な修正があれば別途 Issue を作って進める方向で行きます。
