### ISSUE TITLE
陽性率のグラフの追加について

### ISSUE THREAD

**Issue by heimax222** [code4nara/covid19#260]
## 改善詳細 / Details of Improvement
県の担当課から陽性率の掲載に関して打診があり、詳細を確認したところ以下のような返事がありました。要望内容から、東京版( https://stopcovid19.metro.tokyo.lg.jp/ )のモニタリング指標(6)に相当すると思いますがいかがでしょうか？

県側からの要望と説明
（陽性率の定義）
 ・奈良県では、「陽性率＝陽性者数／新たな検査対象者数」　で計算
 ・ただし、オープンデータ掲載の日毎陽性率は、さらに７日間移動平均としている。
 　計算例：　4/30の７日間移動平均陽性率＝（4/24～4/30の各日の陽性率の計）÷７
 ・「新たな検査対象者数」「陽性者数」ともに、結果判明日ベースで整理しています。
 ・グラフの注釈で上記を記載いただいてはと思います。
 （グラフの表現方法）
 ・棒グラフに重ねて折れ線グラフの方が、分かりやすいように思います。

## スクリーンショット / Screenshot

参考(東京版COVID19対策サイトのモニタリング指標(6))
![image](https://user-images.githubusercontent.com/35659901/83936313-8b120580-a7fd-11ea-9bf1-0d0bca2d43d0.png)

**Comment by heimax222** [comment]
東京都版のモニタリング指標(6)PCR検査数の陽性率を示したのは、移植に際して最も近く、移植しやすいと感じたからです。そのままフルスペックでの移植を考えている訳ではなく、奈良県の出せるデータと調整は必要です。今回、得られた返事から近いグラフが示せそうと感じましたので、参考に示させていただきました。このグラフより、もっと移植しやすそうなグラフがあればお勧めいただきたいのと、我こそはという方がおられましたらご協力の程、よろしくお願いします。

**Comment by heimax222** [comment]
県からの説明と石塚さんのアドバイスから、データに関しては下記のような説明を求める予定です。
①陽性者数＝陽性確認件数という認識か？違うのであればオープンデータの新規項目として「陽性者数」を求める。
②「新たな検査対象者数」をオープンデータの新規項目としての公開を求める。
③「新たな検査対象者数」- 「陽性者数」が「陰性者数」と示して良いか？
上記①～③の確認がとれれば、数値は陽性結果確認日ベースとなりますが、東京版の表現がそのまま流用できると考えますがいかがでしょうか？

**Comment by YasushiIS** [comment]
追加）
・集計表の4/25 、4/26 のデータが足りない。4/1以降の正しいグラフにするには陽性者数だけでも記載してほしい。
・③の「陰性者数」もできれば数字で公開してほしい。不要なミスを避けるため。
補足）
・②のPCR検査数には再検査も含まれると考えられるので、「新たな検査対象者数」は必須。

**Comment by heimax222** [comment]
今見たら、PCR検査数に加えて「県内PCR検査数_陽性確認」「陽性率（7日間移動平均）」の2項目が追加されてますね。この3項目を使って、棒グラフ2本(数の多いPCR検査数を後ろにして、陽性確認数を前)と折れ線グラフを描いてくれないか？ということのようです。
http://www.pref.nara.jp/55168.htm

週末、東京のコードを移植できないかゴソゴソしましたが、かなり作り込みが進んでますね。ざっとやった感じでは動かなかったので、もう少しやってみますがダメかも^^;;どなたか「動いたでー」と言っていただけると助かります。

**Comment by heimax222** [comment]
愛知版( https://stopcovid19.code4.nagoya/ )からの移植を調査中。コンパイルは通ったみたいですが、データの扱いのところでうまくいってない様子orz

![image](https://user-images.githubusercontent.com/35659901/84057191-49967b80-a9f2-11ea-99b8-654043d25a06.png)

![image](https://user-images.githubusercontent.com/35659901/84057548-c6295a00-a9f2-11ea-9598-dec67c744433.png)

![image](https://user-images.githubusercontent.com/35659901/84057104-279cf900-a9f2-11ea-8184-c24c22db6bc7.png)

**Comment by heimax222** [comment]
エラーコメントを頼りに無理やりデータをつなぎあわせて、とりあえず表の表示までは確認できました。愛知版は「日別」「累計」に加え「週別」を独自追加されてるようで、「週別」を外す方が早いのか、そのまま取り込んだ方が早いのかの判断などは、これからです。続きは週末になりそう・・・。
![image](https://user-images.githubusercontent.com/35659901/84386131-c2344c80-ac2b-11ea-8a69-680a3662a0e0.png)

**Comment by heimax222** [comment]
力不足です。すいません。
一応の表示(見た目上の違和感がないレベル)まではこぎつけましたが、スライダーの表示は断念。変数の受け渡しも大きく変わっていたため、左下のリンク表示はソースへの埋め込みで対応しました。このコードをいきなりプルリクするのは忍びないのですが・・・いかがいたしましょう？data.jsonを参照する形にはなっています。
![image](https://user-images.githubusercontent.com/35659901/84591957-5f39f400-ae7d-11ea-822b-c0220c5384ec.png)

**Comment by heimax222** [comment]
現状のコードを https://github.com/heimax222/covid19 の development ブランチにあげておきました。

**Comment by heimax222** [comment]
私自身の方では特に進展はないのですが、現状の出来で公開に向けての議論等を進めるのは困難でしょうか？反応が無いためどうしたものかと・・。

**Comment by heimax222** [comment]
@YasushiIS  様

先日の定例会でお話していたPCR検査数と陽性率の表示ですが、過去の経緯も含めましてこちら( issue #260 )を見てやってください。 https://github.com/heimax222/covid19 の development ブランチのdata.jsonを見ていただくと、追加してある項目も確認できますので、その生成をtoolsのPythonスクリプトに組み込んでいただければ、本番環境でも、そのままで動くと思います。細かな修正点はあると思いますので、時間のある時に、先ずはローカル環境で動作確認だけでもお願いできればと思います。

**Comment by YasushiIS** [comment]
実データで確認する前に、data.json を比較したところいくつか質問があります。

１．陽性率を含むデータ項目に「非確定」があります。奈良県の患者集計表には該当する値はないので、削除してもよいでしょうか？　それともすべて「０」で埋めた方が良いですか？

```
"inspection_persons_summary": {
    "date": "2020/06/08",
    "data":[{"日付":"2020/4/1",
        "検査人数":29,
        "陽性者数":4,
        "陽性率":3.72,
        "非確定":1}
```

２．「合算」が増えてますが、〇と空白はどのような値でしょうか？　そもそもこれらのデータは使われてます？

```
  "inspections_summary": {
    "date": "2020/06/08 18:03",
    "data": [
        {
            "日付": "2020-03-01",
            "小計": 639,
            "合算": "○"
        },
```

**Comment by heimax222** [comment]
早速のdata.jsonの確認ありがとうございます。少し前の作業のため記憶が正しいか確認してみますので、少しお時間ください。愛知県版では、手集計のものと、県発表のものを混在させるため「非確定」のフラグを使ってグラフを切り替えていたと記憶しています。そのため「非確定」のフラグは残す必要があり、値は常に１とする形になると思います。「合算」の方は記憶にないため、おそらく使ってないものと思います。急ぎ確認してみます。

**Comment by YasushiIS** [comment]
余力があれば、ですが、ソースコードもある程度は整理したほうがよさそうです。

data/inspection_persons_summary.csv
など不要そうなファイルもありますし、utils/types.ts には、使われないと思われる型宣言があります。特に下のあたりは、不要であれば削除しておいた方が、あとあと修正するときに混乱せず、コードの見通しは良くなるとは思います。

```
export type MainSummaryDataType = {
  更新日時: string
  検査実施人数: number
  陽性患者数: number
  入院中: number
  軽症中等症: number
  重症: number
  転院: number
  施設入所: number
  死亡: number
  退院: number
}
```

**Comment by YasushiIS** [comment]
ある程度の動作メドができれば、covid19/dev-graph のようなブランチを作って、そのブランチに対して皆で開発を進められるようにする方が良いかと思います。

**Comment by heimax222** [comment]
申し訳ないですが今月はもう余力ありません。つなぎ合わせて動作確認までが精いっぱいでしたので、お気づきの点があり、手を入れられそうであればお願いします。動作メドについては、過去の経緯をみていただければわかりますように、ローカル環境での動作確認は(localhost:3000)しています。念のため石塚さんの方でもすぐに確認いただけるように、githubに一式上げましたので、ご確認いただけましたら助かります。covid19/dev-graphの作成やそこへの配置などは、不慣れな私に代わって行っていただけると助かります。この後「非確定」と「合算」について(localhost:3000で)確認できましたら、ご報告します。

**Comment by heimax222** [comment]
確認してきました。「非確定」及び「合算」ともになくても動作しますので削除してください。また、https://github.com/heimax222/covid19 の development ブランチのdata.jsonは、6月8日分までになりますが奈良県のオープンデータから変換した実データです。スライダーが実装できませんでしたが、グラフ表示側で最新のものから60日分とるようになってますので、データがいくら用意されても直近2か月分しか確認できませんが、多くなりすぎて見にくくなることは無いです。

**Comment by heimax222** [comment]
予定が一つなくなったので、少し時間ができため、githubのブランチ作成方法を調べるところから取り組んでます。ですが、そもそも私のアカウントではcode4naraのcovid19リポジトリでブランチを作成する権限がないような気がしてきました。私のサポートでお手間ばかりかけて申し訳ないです。お調べいただけますか？「covid19/dev-graphの作成やそこへの配置」は石塚さんの方で作業いただく方が早ければ、そちらの方が助かります。

code4naraのcovid19リポジトリでブランチ切り替え用の検索窓に「dev-graph」と入れましたが、「Create branch」の選択肢が出てきませんでした。https://howpon.com/5181
![image](https://user-images.githubusercontent.com/35659901/87216129-94037300-c377-11ea-8223-4d4ba1797908.png)

**Comment by YasushiIS** [comment]
まずは、code4nara/covid19/dev-graph ブランチをつくったのでこのブランチ宛にPRください。
このブランチで、covid19-nara-tool の変換ツールを修正して作成した、data.json で動作確認し、大丈夫になれば development にマージで進めましょう。data.json には、inspection_persons_summary 項目を追加するように修正します。

**Comment by YasushiIS** [comment]
@heimax222 
陽性率の追加等を行った data/data.json を dev-graph にマージしました。
このjsonで問題ないかの確認をお願いします。

**Comment by heimax222** [comment]
陽性率のグラフですが、確認が不十分だったようで、陽性率の折れ線グラフの数字が正しく表現されていませんでした。確認に時間がかかりそうなので、少しお時間ください。

**Comment by heimax222** [comment]
お騒がせしました。原因はわかりましたので、修正方法を検討し後程/dev-graph にプルリクします。何とかなりそうでホッとしました。
![image](https://user-images.githubusercontent.com/35659901/87246920-78898c80-c48b-11ea-92c4-a3bbb0849981.png)

**Comment by YasushiIS** [comment]
下部の説明に「新たな検査対象者数」は不要ではないでしょうか。

まとめサイトの掲載データの中で「結果判明日ベース」に整理し直したのは、陽性者数だけだと思います。
また、グラフにある「検査人数」は、PCR検査数グラフの数字と同じくその日に検査を行った人数でしょうから、それを「結果判明日ベース」に整理できるのが理解できません。

![クリップボード一時ファイル01](https://user-images.githubusercontent.com/6837346/87675353-3a091000-c7b2-11ea-8d15-bb2cbb8f93e6.png)

**Comment by heimax222** [comment]
無事埋め込めたようで良かったです。ありがとうございます。
ご指摘の文言ですが、このissue#260の最初にも記載があります通り、県側からの要望と説明をそのまま記載したものになります。念のためテストサイトのリンクとご指摘の不明点を添えて、県側担当者に確認をお願いしてみます。少しお時間ください。他のグラフと色味を合わせるのであれば、陽性者数の色を蘇芳色に変えておけば良かったと思いました。他は大丈夫そうでしょうか？

**Comment by YasushiIS** [comment]
文言の確認か修正ができ次第、動作確認して公開したいと思いますがいかかでしょう？

**Comment by YasushiIS** [comment]
本番に反映完了したので、チケットをクローズします。
