### ISSUE TITLE
奈良県の報道発表方針の変更により、「入院中」「宿泊療養」のデータ更新が停止され、新たに「入院・療養中」と「入院・入所準備中」で公表されることになりました。

### ISSUE THREAD

**Issue by heimax222** [code4nara/covid19#293]
## 改善詳細 / Details of Improvement
- 県の公表方針の変更があり、公表される項目が一部変更となります。

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/35659901/104315323-226ed200-551e-11eb-9991-7572d4277845.png)

## 期待する見せ方・挙動 / Expected behavior
- 左上の「入院者数の状況」を新しい項目名に合わせるのが望ましいと思います。
　「入院者数の状況」以外のグラフや表には影響無さそうです。
- 自宅療養の扱いがどうなるか未確認です。今回の通知には説明がなく確認してみます。

　通知内容：
　　○更新取りやめ
　　　・入院者数
　　　・宿泊療養者数

　　○更新開始
　　　・入院・療養中
　　　・入院・入所準備中

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by YasushiIS** [comment]
1/12から項目名が変更されたようです。現時点で1/12のデータは、陽性者の属性以外は、処理できず反映されていないようです。
また、この変更で「入院者数と残り病床数」の円グラフもデータ不足で表示できなくなりそうです。対応策としては、入院／療養中と残りの病床＋ホテル室数を表示、でどうでしょう？

**Comment by heimax222** [comment]
「入院者数と残り病床数」の円グラフにも影響あるんですね。公表内容で進めるなら「入院／療養中と残りの病床＋ホテル室数を表示」しか方法は無さそうですね。私が一番見たい病床数の余力が見れなくなるのは残念です。別途、病床使用率(実質の入院者数ですが^^)みたいなのが追加できないか一緒に確認してみます。

**Comment by YasushiIS** [comment]
手元で、エクセルのパースを修正し、状況表の変更をしてみました。
項目の文字数が増えてしまい読みにくいので、図の幅を調整したほうが良さそうです。
![クリップボード01](https://user-images.githubusercontent.com/6837346/104574963-fe380000-5699-11eb-9674-151917609bdc.jpg)

**Comment by YasushiIS** [comment]
状況表を修正してみましたがこれでいかがでしょう？
行ったのは幅の調整、項目の文字数を減らす、単位の人を一番下の行に揃える、です。人の改行は br /を入れるといういい加減な対応です。

いまはlintでエラーが出ているのでエラーをなくしてからプルリクします。

![クリップボード01](https://user-images.githubusercontent.com/6837346/104579051-d13a1c00-569e-11eb-9cfe-5f6b34b0cadc.jpg)

**Comment by heimax222** [comment]
早速ありがとうございます。状況表はこれで良いと思います。後は、病床数の円グラフをどうするかですね。
昨日、電話で下記のような状況説明と要望を出しておきました。
１、今回の変更に対し、影響があるのは「状況表」と「病床数の円グラフ」
２、「状況表」の表記とデータの参照先の変更は比較的小規模な変更のため対応可能
３、「病床数の円グラフ」についても表記とデータの参照先の変更は対応可能。ただし、入院者数と療養者数の合算された数値しかないため、総病床数と療養室数の合算から入院者数と療養者数の合算を引いた、良くわからない数値の円グラフになるがそれで良いか？
特に「病床数の円グラフ」については強めに確認をお願いしましたが、どのようなお返事になるか少し時間がかかるかもです。一旦、円グラフの表示を止めて、再開しておくのもありかと思います。

**Comment by YasushiIS** [comment]
病床円グラフを添付画像のように修正しました。総数は感染症病床数＋宿泊療養室数で、入院・療養中、入院入所準備中、およびそれらを引いた残りで表示しています。宿泊可能な室数と人数は必ずしも一致しないと思いますが、現状このような計算式で表示するしかないように思いますがいかがでしょう？
![クリップボード01](https://user-images.githubusercontent.com/6837346/104685657-e9617800-573e-11eb-83ce-e9bf8e38ee4d.jpg)

開発ページ　https://upbeat-volhard-740574.netlify.app/　にも反映しました。

**Comment by YasushiIS** [comment]
#310 でさらに改善されているので、こちらは Close します。
