### ISSUE TITLE
本番サーバの構築

### ISSUE THREAD

**Issue by YasushiIS** [code4nara/covid19#3]
https://stopcovid19.code4nara.org/
で公開できるように準備する。

**Comment by YasushiIS** [comment]
とりあえず netlify に本番サイトを構築。
最終的には、咲楽屋さん提供のサーバに環境を構築し、本番サーバとしてリリース

**Comment by YasushiIS** [comment]
本番サーバの候補が用意できたつもりです。残作業はDNS（ stopcovid19.code4nara.org ）と、SSL証明書です。
http://210.146.64.10/

**Comment by YasushiIS** [comment]
対応完了
・https化
・faviconの変更
・twitterのリンク変更
残件
・自動デプロイ（git pull を cron で10分おきに実行）
・SSL証明書の自動更新（certbot-auto）
・http => https リダイレクト

**Comment by shige2313** [comment]
> 残件
> ・SSL証明書の自動更新（certbot-auto）
> ・http => https リダイレクト

http => https リダイレクトを設定するとcertbot-autoの更新時に動かなくなるので、Let's Encryptが参照するフォルダだけリダイレクト対象外に設定する必要があります

**Comment by YasushiIS** [comment]
git pull を cron で10分おきに実行するように設定しました。
自残は
・SSL証明書の自動更新（certbot-auto）
のみとし、http => https リダイレクト自動更新は必要性が低いので無しにします

**Comment by YasushiIS** [comment]
本番リリース（＝masterの更新）に合わせて必要な json を
https://stopcovid19.code4nara.org/api/
に配置する。元データが自動入手できるようになれば自動更新とする。

**Comment by YasushiIS** [comment]
certbot-auto を cron 実行を設定。以上このissueをcloseします、
