### ISSUE TITLE
円グラフでの負の値が正の値として表示される

### ISSUE THREAD

**Issue by Radibac** [code4nara/covid19#305]
## 起こっている問題 / The Problem
- 2021/4/14現在感染者数(728)は奈良県内の病床数(630)より多いため、便宜上残り病床数は負の数（-98）となっています。しかし、病床の占有率を示す円グラフは残り病床数が相当大きな割合で表示されており、実態を反映したグラフになっていません。

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/38759169/114713535-2fdd6780-9d6c-11eb-923d-d8df1f55f586.png)

## 期待する見せ方・挙動 / Expected Behavior
- 残り病床数が0を下回る場合には円グラフ以外の方法で病床が逼迫していることを表す手段を検討してほしく思います。

## 起こっている問題の再現手段 / Steps to Reproduce
1. サイトにアクセスするのみで件のグラフが表示されます。

## 動作環境・ブラウザ / Environment
-  Windows / Android
- Chrome / Firefox
上記の現象を確認した組み合わせは以下の通りです。

- Windows 10 & Chrome 89.0.4389.114
- Android 11 & Chrome 89.0.4389.105

**Comment by YasushiIS** [comment]
奈良県のオープンデータ（ http://www.pref.nara.jp/55168.htm ）内の4/20時点の集計表では

宿泊療養室数                254
感染症対応病床数        384
入院・療養中数           451
入院・入所準備中数    424

となっています。
現状、ここから総病床数を、宿泊療養室数＋感染症対応病床数   = 638 
残り病床数を、総病床数ー入院・療養中数 ー入所準備中数 で計算しているため、-237 になってます。

円グラフでマイナス表記があるのがおかしいので、円グラフではマイナスの残り病床を表示しない（内部的に０）に修正します。
一方で、どこかに、病床が237 足りない（4/20時点で）という表現を追加したいです。

**Comment by YasushiIS** [comment]
取り急ぎ、残り病床（＋療養室）数の計算式を修正し、マイナス表示を回避しました。
![image](https://user-images.githubusercontent.com/6837346/115527087-b09be680-a2cb-11eb-9cfe-2ffe30a7118e.png)

この円グラフでは、残り病床＋療養室数が、入院・入所準備中を下回っていることがわからないので他の表示があった方が良さそうに思います。

**Comment by YasushiIS** [comment]
data.json のみの変更で、表示周りのソースは変更していないのに、マウスオーバーでの表示が出なくなりました。
開発環境などでも確認します。

**Comment by Radibac** [comment]
対応感謝します。ありがとうございます！

**Comment by YasushiIS** [comment]
いまの円グラフの表示をどうするかも #308 に含めてましょう。
円グラフの修正に関しては完了として close します。
