### ISSUE TITLE
円グラフで表示している病床数の数字が誤って表示されている

### ISSUE THREAD

**Issue by heimax222** [code4nara/covid19#314]
## 起こっている問題 / The Problem
- 病床数がオープンデータで公表されている数字(宿泊療養室数424床＋感染症対応病床数395床の計819床)より
　多く(1030床、2021/05/04現在)表示されている。

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/35659901/116958810-bf749700-acd6-11eb-9b42-624280ae630c.png)

## 期待する見せ方・挙動 / Expected Behavior
- 公開情報通りに表示する。

## 起こっている問題の再現手段 / Steps to Reproduce
- 最新情報に更新

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by heimax222** [comment]
日々少しづつ増えているような気がするため、どこか計算している部分で間違っているのかも。

**Comment by YasushiIS** [comment]
Chart.js の円グラフの基本レンダリング（？）で、合計は、データに含まれる各要素の合計になっている様です。円グラフで表示するものですから当然ですね。
なので5/3時点の1030は、「入院・療養中数」＋「 入院・入所待機中」の合計なのでコードとしての動作は正しいです。

**Comment by YasushiIS** [comment]
グラフとしては誤りなので、対応としては
１．グラフを変えずにタイトルを「現在患者数に対する入院・療養中の割合」として、「総病床＋療養室数」を「現在患者数」に変更
２．タイトルを変えずにグラフを、感染症病床＋療養室数に対する入院・療養者数に修正する
３．円グラフを、１と２の２種類表示する。
という選択肢かな、と思います。
とりあえず、３の方向で修正してみます。
（追記）１、２とも、重症者用のベッド数はオープンデータに含まれていないものの、入院・療養者数に重症者数が含まれていると思われるので、これを分けての表示もできそうです。

**Comment by YasushiIS** [comment]
手元で添付の様に直してみました。
これに合わせて covid19-nara-tools  json変換ツールも修正します。
![image](https://user-images.githubusercontent.com/6837346/116970366-cc9f7f00-acf2-11eb-8909-20de7007a62c.png)

**Comment by heimax222** [comment]
早速ありがとうございます。怪我の功名というか、2つに分ける案いいですね。
①入院・療養者数に重症者数が含まれるかどうか確認しておきます。
②「入院・入所準備中数」は少し長くなりますが「入院・入所待機中、自宅療養中」としましょう。
上記、2点が気になりましたが、現在の表記が不適切なため、取り急ぎ提案いただいた内容で更新しませんか？

**Comment by YasushiIS** [comment]
奈良県ホームページの状況表と、発表資料のPDFを見ると、入院・療養者数に重症者数が含まれる以外はありえない、と思っています。
![image](https://user-images.githubusercontent.com/6837346/116977562-8ac80600-acfd-11eb-8cc1-2bc9af346f66.png)

http://www.pref.nara.jp/secure/247637/0504houdou.pdf

**Comment by YasushiIS** [comment]
データの項目として、奈良県のPDF資料の単位は、「使用病床数」＝ベッド数＝人数だが、「入所室数」＝室数≠人数であることに留意しないといけないかもしれません。

**Comment by YasushiIS** [comment]
グラフを修正したものを開発・テストページにあげました。変換ツールの確認ができればリリースに向けて動きたいと思います。
https://upbeat-volhard-740574.netlify.app/

**Comment by heimax222** [comment]
いい感じじゃないかと思います。一つ提案ですが、「現在感染者の各状況の割合」を右の一番上にもってきませんか？そうすると一つずつずれて、並びが良くなると思います。
![image](https://user-images.githubusercontent.com/35659901/117008529-cc6ca700-ad25-11eb-8fc5-d99361413a38.png)

**Comment by YasushiIS** [comment]
いまの病床・療養室数の円グラフは、「入院調整中・自宅待機中」の人数は含んでいない旨の注釈を追加したいと考えています。理由としては、この円グラフでは、残り病床の数が表示されていて、すぐに入れる印象があるので、あくまで利用状況を示していると分かりやすくするため、です。

**Comment by YasushiIS** [comment]
感染者状況の割合を入院者数の状況の次に移動し、文言修正したものを pull request しました。
