### ISSUE TITLE
7/8以降のデータが更新されていない

### ISSUE THREAD

**Issue by dolciss** [code4nara/covid19#331]
## 起こっている問題 / The Problem
- 2022/07/08-2022/07/15、2022/07/17以降のデータが更新されていない。強制リロードしても変わらない。

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/3786294/180155496-40b5432c-9b48-4962-9e02-415081c5818f.png)

## 期待する見せ方・挙動 / Expected Behavior
- データが更新される

## 起こっている問題の再現手段 / Steps to Reproduce
1. 任意のブラウザで表示

## 動作環境・ブラウザ / Environment
- Windows
- Chrome

**Comment by dolciss** [comment]
奈良県のオープンデータ http://www.pref.nara.jp/55168.htm の 02 の集計表において、
日付のフォーマットが正しくないことにより、反映できていないと思われます。
（7/8の表記が「2022007-08」となっています。以降同様）
オープンデータの方が誤っていますので、対応いただけるかどうかはご判断をお願いいたします。

**Comment by YasushiIS** [comment]
ご指摘ありがとうございます。原因も調査いただいた通りです。
まずは奈良県側に連絡して、オープンデータ側が変わらないようでしたら改めて検討したいと考えています。

**Comment by YasushiIS** [comment]
奈良県の防災統括室に連絡したところ、すぐにオープンデータの集計表が修正されました。
まとめサイトの陽性者グラフも、自動更新で正しく表示されるようにななったので、このIssueをクローズします。

**Comment by dolciss** [comment]
ご対応ありがとうございました。
