### ISSUE TITLE
リスト表示の下にある「※退院には、死亡退院を含む」の削除

### ISSUE THREAD

**Issue by heimax222** [code4nara/covid19#39]
## 改善詳細 / Details of Improvement
　リスト表示の下にある「※退院には、死亡退院を含む」の表記は、現状の奈良で発表されているデータからは読み取れないので、現状では不要だと思います。

![image](https://user-images.githubusercontent.com/35659901/77253870-c4c47d00-6ca0-11ea-9466-ca606a5ba9b0.png)

**Comment by YasushiIS** [comment]
テストサイトに反映済み。

**Comment by YasushiIS** [comment]
本番に反映済みなので、issueをクローズしあｍす。
