### ISSUE TITLE
愛知県版のリンクが残っている

### ISSUE THREAD

**Issue by kwaka1208** [code4nara/covid19#53]
## 起こっている問題 / The Problem
- [貢献の仕方](https://github.com/kwaka1208/covid19/blob/development/.github/CONTRIBUTING.md)の内容がCode for Nagoyaや愛知県版のままになっている。

## 期待する見せ方・挙動 / Expected Behavior
- 奈良版の情報が表示されるようにする。

## 起こっている問題の再現手段 / Steps to Reproduce
1. [貢献の仕方](https://github.com/kwaka1208/covid19/blob/development/.github/CONTRIBUTING.md)にアクセス。
2. 次のリンク先を確認「コミュニケーションへの参加方法」の中の「こちらから登録」、「good first issue ラベルのついたもの」、「開発サイト」、「本番サイト」

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kwaka1208** [comment]
Slack登録用のURLと開発サイトのURL以外は手元で修正したので、この2つを教えていただければPR送ります。そもそも開発サイトはあるのかな？

**Comment by YasushiIS** [comment]
ご指摘ありがとうございます。以下の情報に修正いただけますでしょうか？

slack招待URL：  https://join.slack.com/t/code-for-all-nara/shared_invite/zt-d1xw9fxt-fgsRMzVzXD9ojHtaoBb9_w
開発サイト：　https://upbeat-volhard-740574.netlify.com/ 
本番サイト：　https://stopcovid19.code4nara.org/

slackの招待URLは無期限のものを取得し直しました。
