### ISSUE TITLE
「新型コロナウイルス感染症が心配なときに」ページ（フロー図）を奈良県版に追加

### ISSUE THREAD

**Issue by YasushiIS** [code4nara/covid19#60]
## 改善詳細 / Details of Improvement
- 「新型コロナウイルス感染症が心配なときに」ページを追加
- 追加する内容は東京都のような内容で、電話番号等を公表情報に合わせる
https://stopcovid19.metro.tokyo.lg.jp/flow

## 期待する見せ方・挙動 / Expected behavior
- 奈良県版「新型コロナウイルス感染症が心配なときに」ページが表示される

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by YasushiIS** [comment]
非公式版なので、とりあえず作成宇してみる方向で進めます。

**Comment by heimax222** [comment]
右上の相談先の枠内の表現ですが、
　感染疑いが最初から強い方→帰国者・接触者相談センターhttp://www.pref.nara.jp/#003
　不安な方　　　　　　　　→一般的な相談窓口http://www.pref.nara.jp/#002
だと思いますので以下のように変更してみてはいかがでしょう。
①帰国者・接触者相談センターの情報と保健所情報の位置を上下入れ替える。
②「帰国者・接触者相談センター」上部の「奈良県庁」の文字を少し大きくする。
③「各保健所」を公式ページの表現に合わせて「一般的な相談窓口」とする。
④「一般的な相談窓口」に「奈良県庁」も追加。
⑤「一般的な相談窓口」も平日と土日祝で対応が違うため、添付のサンプルのように分けて表記する。
以上です。ぴったりのフォントが見つからず文字サイズなどが少しいびつになってますが、その辺りは修正しやすい方向で進めてみてください。

![image](https://user-images.githubusercontent.com/35659901/78892067-a5509100-7aa3-11ea-82f5-c00bb067339f.png)

**Comment by miiton** [comment]
@heimax222 はい、私も最初はそうなのかなと思ったのですが、

![奈良県公式ホームページ 2020-04-09 23-12-23](https://user-images.githubusercontent.com/468745/78904553-ac819a00-7ab7-11ea-9ad7-9884505da871.png)

この部分の記載を見て上下を入れ替えてコミットしています（プルリクに意図を書くべきでした）

書くとしたら

- 日中 : 奈良県庁
- 夜間 : 各保健所

でしょうか？

**Comment by heimax222** [comment]
@miiton  さん

お疲れ様です。丁寧な説明ありがとうございます。はやしだです。

　確かにおっしゃる通り、諸条件がそろった緊急性の高い状態の方に対しては保健所で24時間対応しますとなっていますね。早合点しました。

　一方で、現状の表現では保健所の負荷が高くなりすぎるのを心配します。上にあるものから電話をかける可能性が高いと考えました。また24時間対応もわざわざ特例条件をつけていることを見ると、体制が不十分なことが考えられますので、24時間対応が表に出すぎるのもどうかと思います。日中はコロナに関しては「帰国者・接触者相談センター」に相談してもらって、通常業務も大切な保健所の負担を下げたいというふうに感じるのですが、その点についてはいかがでしょう？

**Comment by heimax222** [comment]
とりあえず、先程のイメージに但し書きを追加してみました。
![image](https://user-images.githubusercontent.com/35659901/78912388-7f86b480-7ac2-11ea-9fb8-8f58450535c2.png)

**Comment by miiton** [comment]
左側をいじらない前提でいくと、こういうマッピングですが、

![flow-print sketch 2020-04-10 07-58-29](https://user-images.githubusercontent.com/468745/78947886-a6b0a680-7b01-11ea-83e1-67a6329fce77.png)

奈良県から指示があったわけではない以上、「負荷をかけない」という点を優先してとりあえず実装するべきで @heimax222 さんの案で修正しようと思います🙋‍♂️

**Comment by miiton** [comment]
とりいそぎ画像で

![flow-print sketch 2020-04-10 08-14-05](https://user-images.githubusercontent.com/468745/78948434-4458a580-7b03-11ea-80c8-9f6beb780328.png)

**Comment by heimax222** [comment]
ご理解いただきありがとうございます。
マッピングでの示し方など勉強になります。
引き続きよろしくお願いいたします。

**Comment by YasushiIS** [comment]
一旦現状でリリースし、表現修正は継続して行っていきましょう

**Comment by heimax222** [comment]
@miiton さん
相談しようと思ったらもう実装されてる。滅茶苦茶早いですね！

公式のページを見ていてFAXの情報があるのが気になっていたのですがこういう理由なんですね。
![image](https://user-images.githubusercontent.com/35659901/78993852-ac49d300-7b79-11ea-920b-1f44d9a019ac.png)

もうすでにパツパツですが、FAX情報も追加しませんか？
今のレイアウトに追加するなら、こんな感じでしょうか。
FAX相談票はいい感じのを公開してくれてますね。
PDF版：http://www.pref.nara.jp/secure/222718/coronafaxnara0409.pdf
Excel版：http://www.pref.nara.jp/secure/222718/coronafaxnara0409.xls

![image](https://user-images.githubusercontent.com/35659901/78995468-5c6d0b00-7b7d-11ea-8574-d15d02ef4a59.png)
