### ISSUE TITLE
サイドバーに一般電話相談窓口、帰国者・接触者相談センター、教育委員会の発表、労働関係の電話相談リンクの追加

### ISSUE THREAD

**Issue by YasushiIS** [code4nara/covid19#77]
## 改善詳細 / Details of Improvement
- サイドバーに以下のリンクを追加する
一般電話相談窓口 　帰国者・接触者相談センター　教育委員会の発表 　労働関係の電話相談
参考：https://hazard.yahoo.co.jp/article/covid19nara

## 期待する見せ方・挙動 / Expected behavior
- サイドバーに以下のリンクが表示される
一般電話相談窓口 　帰国者・接触者相談センター　教育委員会の発表 　労働関係の電話相談

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kwaka1208** [comment]
こちらのIssueへの対応を一度検討してみていただけますか？@kogame16 @makota36 @Haruto-Ando

**Comment by YasushiIS** [comment]
開発サイトの動作で問題がないので、次のリリースで本番デプロイします。
デプロイ時にクローズします。
